modified 2step seed
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@2840 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/2step b/playground/eman.seeds/2step
--- a/playground/eman.seeds/2step
+++ b/playground/eman.seeds/2step
@@ -4,7 +4,7 @@
 function die() { echo "$@" | tee FAILED >&2; exit 1 ; }
 set -o pipefail
 
-TESTBLEU=/home/bojar/diplomka/granty/euromatrix/treedecode/trunk/testbleu.asm
+#TESTBLEU=/home/bojar/diplomka/granty/euromatrix/treedecode/trunk/testbleu.asm
 
 PLAYGROUND=`eman path` # eman playground directory
 
@@ -15,7 +15,7 @@ eman \
   defvar TESTCORP help="the corpus for evaluation" inherit=PHASE1MERT \
   defvar PHASE1TESTCORP inherit=PHASE2MERT:TESTCORP \
   defvar SRCAUG inherit=PHASE1MERT \
-  defvar REFAUG inherit=PHASE1MERT \
+  defvar REFAUG inherit=PHASE2MERT:REFAUG \
   defvar MIDAUG inherit=PHASE2MERT:SRCAUG \
   defvar SEARCH help="beam or cube" default=cube \
   defvar MOSESFLAGS help="any further flags" default='' \
@@ -30,21 +30,28 @@ eman \
 # Set local bash variables
 eval `eman bash-loadvars`
 
-BINARIESDIR=`eman path $BINARIES`
-SCRIPTS_ROOTDIR="`cat $BINARIESDIR/scripts.rootdir`"
-MOSESCMD="$BINARIESDIR/bin/moses"
+#BINARIESDIR=`eman path $BINARIES`
+#SCRIPTS_ROOTDIR="`cat $BINARIESDIR/scripts.rootdir`"
+#MOSESCMD="$BINARIESDIR/bin/moses"
 
-eman add-tag "$TAGPREF"SRC"$SRCAUG".MID"$MIDAUG".TGT"$REFAUG".$SEARCH$STACK.FIRST.`cat $PHASE1MERT/eman.tag`.SECOND.`cat $PHASE2MERT/eman.tag` .
+MOSESDIR="$(eman path $BINARIES)"
+SCRIPTS_ROOTDIR="$MOSESDIR/moses/scripts"
+MOSESCMD="$MOSESDIR/bin/moses"
+
+#eman add-tag "$TAGPREF"SRC"$SRCAUG".MID"$MIDAUG".TGT"$REFAUG".$SEARCH$STACK.FIRST.`cat $PHASE1MERT/eman.tag`.SECOND.`cat $PHASE2MERT/eman.tag` .
 
 # Stop here if we are just initing ourselves
 [ -z "$INIT_ONLY" ] || exit 0
 
-$PLAYGROUND/augmented_corpora/augment.pl --dump $TESTCORP/$SRCAUG > evaluation.in || die "evaluation.in"
-$PLAYGROUND/augmented_corpora/augment.pl --dump $TESTCORP/$REFAUG > evaluation.ref.0 || die "evaluation.ref"
+#$PLAYGROUND/augmented_corpora/augment.pl --dump $TESTCORP/$SRCAUG > evaluation.in || die "evaluation.in"
+#$PLAYGROUND/augmented_corpora/augment.pl --dump $TESTCORP/$REFAUG > evaluation.ref.0 || die "evaluation.ref"
+
+$PLAYGROUND/corpman --dump $TESTCORP/$SRCAUG > evaluation.in || die "evaluation.in"
+$PLAYGROUND/corpman --dump $TESTCORP/$REFAUG > evaluation.ref.0 || die "evaluation.ref"
 
 srccorpstep=$($PLAYGROUND/corpman --init $TESTCORP/$SRCAUG | cut -f1)
 [ ! -z "$srccorpstep" ] || die "Missing source corpus"
-tgtcorpstep=$($PLAYGROUND/corpman --init $TESTCORP/$TGTAUG | cut -f1)
+tgtcorpstep=$($PLAYGROUND/corpman --init $TESTCORP/$REFAUG | cut -f1)
 [ ! -z "$tgtcorpstep" ] || die "Missing target corpus"
 eman add-deps . $srccorpstep $tgtcorpstep
 
@@ -116,7 +123,7 @@ function mkcorpus() {
   fi
 }
 mkcorpus $TESTCORP/$SRCAUG evaluation.in
-mkcorpus $TESTCORP/$TGTAUG evaluation.ref.0
+mkcorpus $TESTCORP/$REFAUG evaluation.ref.0
 
 gunzip evaluation.in.gz
 gunzip evaluation.ref.0.gz
@@ -137,42 +144,46 @@ echo export SCRIPTS_ROOTDIR=${SCRIPTS_ROOTDIR}
 
 # clone some important executables
 $PLAYGROUND/../scripts/wiseln $MOSESCMD ./moses || die "Failed to clone moses"
-$PLAYGROUND/../scripts/wiseln $TESTBLEU ./testbleu || die "Failed to clone testbleu"
+#$PLAYGROUND/../scripts/wiseln $TESTBLEU ./testbleu || die "Failed to clone testbleu"
 
-if [ $PHASE1TESTCORP == $TESTCORP ]; then
-  echo "No need to translate first step, reuse output from $PHASE1MERT"
-  cp \$phase1dir/evaluation.opt.out ./evaluation.mid
-  cp \$phase1dir/evaluation.opt.ali ./evaluation.mid.ali
-else
-  echo "Will translate evaluation.in with $PHASE1MERT"
+gunzip $PLAYGROUND/../src/testbleu.gz -c > ./testbleu \
+|| die "Cannot extract testbleu binary!"
+chmod +x ./testbleu
 
-  ## Clone the moses.ini and source files
-  mkdir phase1model || die "mkdir failed"
-  cd phase1model || die "mkdir failed"
-  \$SCRIPTS_ROOTDIR/training/clone_moses_model.pl \\
-    \$phase1dir/moses.abs.ini || die "clone failed"
-  # Absolutize
-  \$SCRIPTS_ROOTDIR/training/absolutize_moses_model.pl ./moses.ini \\
-    > moses.abs.ini || die "Absolutize failed"
-  # Apply weights
-  $PLAYGROUND/tools/apply_weights_from_moses_ini.pl \\
-    \$phase1dir/mert-tuning/moses.ini < moses.abs.ini > moses.opt.ini \\
-    || die "Apply failed"
-  cd ..
-  # Filter for our input
-  \$SCRIPTS_ROOTDIR/training/filter-model-given-input.pl filtered-for-phase1 \\
-    ./phase1model/moses.opt.ini evaluation.in \\
-    || die "Filter for phase 1 failed"
+#if [ $PHASE1TESTCORP == $TESTCORP ]; then
+#  echo "No need to translate first step, reuse output from $PHASE1MERT"
+#  cp \$phase1dir/evaluation.opt.out ./evaluation.mid
+#  cp \$phase1dir/evaluation.opt.ali ./evaluation.mid.ali
+#else
+echo "Will translate evaluation.in with $PHASE1MERT"
 
-  $MOSESPARALLELIZER \\
-    -input-file ./evaluation.in \\
-    -alignment-output-file ./evaluation.mid.ali \\
-    -config ./filtered-for-phase1/moses.ini \\
-    | sed 's/^ *//' \\
-    | sed 's/ *$//' \\
-    > evaluation.mid \\
-     || die "Translation of phase 1 failed"
-fi
+## Clone the moses.ini and source files
+mkdir phase1model || die "mkdir failed"
+cd phase1model || die "mkdir failed"
+\$SCRIPTS_ROOTDIR/training/clone_moses_model.pl \\
+  \$phase1dir/moses.abs.ini || die "clone failed"
+# Absolutize
+\$SCRIPTS_ROOTDIR/training/absolutize_moses_model.pl ./moses.ini \\
+  > moses.abs.ini || die "Absolutize failed"
+# Apply weights
+$PLAYGROUND/tools/apply_weights_from_moses_ini.pl \\
+  \$phase1dir/mert-tuning/moses.ini < moses.abs.ini > moses.opt.ini \\
+  || die "Apply failed"
+cd ..
+# Filter for our input
+\$SCRIPTS_ROOTDIR/training/filter-model-given-input.pl filtered-for-phase1 \\
+  ./phase1model/moses.opt.ini evaluation.in \\
+  || die "Filter for phase 1 failed"
+
+$MOSESPARALLELIZER \\
+  -input-file ./evaluation.in \\
+  -alignment-output-file ./evaluation.mid.ali \\
+  -config ./filtered-for-phase1/moses.ini \\
+  | sed 's/^ *//' \\
+  | sed 's/ *$//' \\
+  > evaluation.mid \\
+  || die "Translation of phase 1 failed"
+#fi
 
 ## Clone the moses.ini and source files
 mkdir phase2model || die "mkdir failed"
