renamed makecorpus.pl to corpman and the corpman seed to 'corpus'
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@2667 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/2step b/playground/eman.seeds/2step
--- a/playground/eman.seeds/2step
+++ b/playground/eman.seeds/2step
@@ -42,9 +42,9 @@ eman add-tag "$TAGPREF"SRC"$SRCAUG".MID"$MIDAUG".TGT"$REFAUG".$SEARCH$STACK.FIRS
 $PLAYGROUND/augmented_corpora/augment.pl --dump $TESTCORP/$SRCAUG > evaluation.in || die "evaluation.in"
 $PLAYGROUND/augmented_corpora/augment.pl --dump $TESTCORP/$REFAUG > evaluation.ref.0 || die "evaluation.ref"
 
-srccorpstep=$($PLAYGROUND/makecorpus.pl --init $TESTCORP/$SRCAUG | cut -f1)
+srccorpstep=$($PLAYGROUND/corpman --init $TESTCORP/$SRCAUG | cut -f1)
 [ ! -z "$srccorpstep" ] || die "Missing source corpus"
-tgtcorpstep=$($PLAYGROUND/makecorpus.pl --init $TESTCORP/$TGTAUG | cut -f1)
+tgtcorpstep=$($PLAYGROUND/corpman --init $TESTCORP/$TGTAUG | cut -f1)
 [ ! -z "$tgtcorpstep" ] || die "Missing target corpus"
 eman add-deps . $srccorpstep $tgtcorpstep
 
@@ -103,15 +103,15 @@ set -o pipefail
 function die() { echo "\$@" >&2 ; echo FAILED > \$mydir/eman.status ; exit 1 ; }
 
 function mkcorpus() {
-  $PLAYGROUND/makecorpus.pl --wait \$1 || die "Failed to prepare \$1"
-  step_file_col=(\$($PLAYGROUND/makecorpus.pl \$1))
+  $PLAYGROUND/corpman --wait \$1 || die "Failed to prepare \$1"
+  step_file_col=(\$($PLAYGROUND/corpman \$1))
   if [ "\${step_file_col[2]}" == "-1" ]; then
     $PLAYGROUND/../scripts/wiseln $PLAYGROUND/\${step_file_col[0]}/\${step_file_col[1]} \\
       \$2.gz \
     || die "Failed to clone \$2 corpus \$1"
   else
     echo "Selecting the column from \$step_file_col"
-    eval \$($PLAYGROUND/makecorpus.pl --cmd $1) \\
+    eval \$($PLAYGROUND/corpman --cmd $1) \\
     | gzip -c > \$2.gz
   fi
 }
diff --git a/playground/eman.seeds/align b/playground/eman.seeds/align
--- a/playground/eman.seeds/align
+++ b/playground/eman.seeds/align
@@ -31,9 +31,9 @@ GIZAWRAPPER=$PLAYGROUND/../scripts/gizawrapper.pl
 [ -x $GIZAWRAPPER ] || die "gizawrapper not found: $GIZAWRAPPER"
 
 # add source and target corpora to deps
-srccorpstep=$($PLAYGROUND/makecorpus.pl --init $CORPUS/$SRCALIAUG | cut -f1)
+srccorpstep=$($PLAYGROUND/corpman --init $CORPUS/$SRCALIAUG | cut -f1)
 [ ! -z "$srccorpstep" ] || die "Missing source corpus"
-tgtcorpstep=$($PLAYGROUND/makecorpus.pl --init $CORPUS/$TGTALIAUG | cut -f1)
+tgtcorpstep=$($PLAYGROUND/corpman --init $CORPUS/$TGTALIAUG | cut -f1)
 [ ! -z "$tgtcorpstep" ] || die "Missing target corpus"
 
 eman add-deps . $srccorpstep $tgtcorpstep
@@ -65,15 +65,15 @@ export SCRIPTS_ROOTDIR=$GIZASTEP/moses/scripts
 echo SCRIPTS_ROOTDIR=\$SCRIPTS_ROOTDIR
 
 function mkcorpus() {
-  $PLAYGROUND/makecorpus.pl --wait \$1 || die "Failed to prepare \$1"
-  step_file_col=(\$($PLAYGROUND/makecorpus.pl \$1))
+  $PLAYGROUND/corpman --wait \$1 || die "Failed to prepare \$1"
+  step_file_col=(\$($PLAYGROUND/corpman \$1))
   if [ "\${step_file_col[2]}" == "-1" ]; then
     $PLAYGROUND/../scripts/wiseln $PLAYGROUND/\${step_file_col[0]}/\${step_file_col[1]} \\
       corpus.\$2.gz \
     || die "Failed to clone \$2 corpus \$1"
   else
     echo "Selecting the column from \$step_file_col"
-    eval \$($PLAYGROUND/makecorpus.pl --cmd $1) \\
+    eval \$($PLAYGROUND/corpman --cmd $1) \\
     | gzip -c > corpus.\$2.gz
   fi
 }
@@ -109,7 +109,7 @@ for s in $(echo $ALISYM | tr , ' '); do \\
   || die "Failed to append corpman.info"
   i=\$((\$i+1))
 done
-rm $PLAYGROUND/makecorpus.index # force to reindex
+rm $PLAYGROUND/corpman.index # force to reindex
 
 # Standard command footer
 echo Done.
diff --git a/playground/eman.seeds/corpus b/playground/eman.seeds/corpus
--- a/playground/eman.seeds/corpus
+++ b/playground/eman.seeds/corpus
@@ -1,5 +1,5 @@
 #!/bin/bash
-# eman step to support makecorpus.pl
+# eman step to support corpman
 # Three modes of operation:
 #   RUN_COMMAND=...  apply the given pipe to the given input corpus
 #                    you *may* leave STEPNAME etc empty if the command produces
@@ -103,7 +103,7 @@ nl=\$(zcat corpus.txt.gz | wc -l)
 [ "\$nl" -eq $OUTLINECOUNT ] \\
 || die "Mismatched number of lines, expected $OUTLINECOUNT, got \$nl"
 
-rm -f \$mydir/../makecorpus.index || echo "Failed to force reindexing"
+rm -f \$mydir/../corpman.index || echo "Failed to force reindexing"
 
 echo Done.
 eman succeed \$mydir
