corpman register
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@2766 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/align b/playground/eman.seeds/align
--- a/playground/eman.seeds/align
+++ b/playground/eman.seeds/align
@@ -105,9 +105,8 @@ srclen=\`zcat corpus.src.gz | wc -l\`
 echo "Aligned, now create corpman info."
 i=1
 for s in $(echo $ALISYMS | tr , ' '); do \\
-  echo "alignment.gz	\$i	$CORPUS	\$s-$ALILABEL	ali	\$srclen" \\
-    >> corpman.info \\
-  || die "Failed to append corpman.info"
+  $PLAYGROUND/corpman register -- alignment.gz \$i $CORPUS \$s-$ALILABEL ali \$srclen \\
+  || die "Failed to register corpus"
   i=\$((\$i+1))
 done
 rm $PLAYGROUND/corpman.index # force to reindex
