Support for storing and re-using mgiza++ model in seed align. Not yet implemented in gizawrapper.pl.

diff --git a/playground/eman.seeds/align b/playground/eman.seeds/align
--- a/playground/eman.seeds/align
+++ b/playground/eman.seeds/align
@@ -9,6 +9,10 @@ PLAYGROUND=`eman path` # eman playground directory
 # Ensure all the required variables are set (or provide the default)
 eman \
   defvar GIZASTEP type=reqstep help='where is GIZA/mGIZA and symal compiled' \
+  defvar USEMODEL type=optstep default='' \
+    help='use MGiza to align the data using an existing model, implies KEEPMODEL=no' \
+  defvar KEEPMODEL default='yes' \
+    help='store the model, only has effect when MGiza is used' \
   defvar CORPUS help='the corpus name' \
   defvar SRCALIAUG help='lang+factors for the source side' \
   defvar TGTALIAUG help='lang+factors for the target side' \
@@ -27,6 +31,13 @@ eval `eman bash-loadvars`
 if [ -z "$ALILABEL" ]; then
   export ALILABEL=$(echo $SRCALIAUG-$TGTALIAUG | tr '+.' '--')
   eman defvar ALILABEL
+fi
+
+# do not keep the model if we don't create one
+if [ -n "$USEMODEL" ] ; then
+  MODELPATH="$(eman path $USEMODEL)/model"
+  export KEEPMODEL=no
+  eman defvar KEEPMODEL
 fi
 
 GIZAWRAPPER=$PLAYGROUND/../scripts/gizawrapper.pl
@@ -114,38 +125,32 @@ mkcorpus $CORPUS/$TGTALIAUG tgt
 tempdir=$TMPDIR
 [ -d "\$tempdir" ] || tempdir=/tmp
 
-if [ "`echo $GIZASTEP | grep 's.mgiza'`" ]; then
+[ -z "`echo $GIZASTEP | grep 's.mgiza'`" ] || ismgiza=yes
 
-    $GIZAWRAPPER \\
-        corpus.src.gz corpus.tgt.gz \\
-        --lfactors=0 --rfactors=0 \\
-        --tempdir=\$tempdir \\
-        --mgizadir=$GIZASTEP/bin \\
-        --mgizacores=$EMAN_CORES \\
-        --dirsym=$ALISYMS \\
-        --drop-bad-lines \\
-    | gzip -c > alignment.gz \
-    || die "Failed to align the corpus"
+wrapperargs="corpus.src.gz corpus.tgt.gz \\
+  --lfactors=0 --rfactors=0 \\
+  --tempdir=\$tempdir \\
+  --dirsym=$ALISYMS \\
+  --drop-bad-lines \\
+"
 
+if [ \$ismgiza = yes ]; then
+  wrapperargs="\$wrapperargs --mgizadir=$GIZASTEP/bin --mgizacores=$EMAN_CORES"
+  [ $KEEPMODEL = yes ] && wrapperargs="\$wrapperargs --keep"
+  [ -z "$USEMODEL" ] || wrapperargs="\$wrapperargs --mgiza-model=$MODELPATH"
 else
-
-    $GIZAWRAPPER \\
-        corpus.src.gz corpus.tgt.gz \\
-        --lfactors=0 --rfactors=0 \\
-        --tempdir=\$tempdir \\
-        --bindir=$GIZASTEP/bin \\
-        --dirsym=$ALISYMS \\
-        --drop-bad-lines \\
-    | gzip -c > alignment.gz \
-    || die "Failed to align the corpus"
-
+  wrapperargs="\$wrapperargs --bindir=$GIZASTEP/bin"
 fi
+
+$GIZAWRAPPER \\
+\$wrapperargs 2> gizawrapper.log \\
+| gzip -c > alignment.gz \\
+|| die "Failed to align the corpus"
 
 alilen=\`zcat alignment.gz | wc -l\`
 srclen=\`zcat corpus.src.gz | wc -l\`
 [ \$alilen == \$srclen ] \
   || die "Mismatched file lengths: ali \$alilen, src \$srclen"
-
 
 echo "Aligned, now register alignments in corpman."
 i=1
@@ -155,6 +160,17 @@ for s in $(echo $ALISYMS | tr , ' '); do \\
   i=\$((\$i+1))
 done
 rm $PLAYGROUND/corpman.index # force to reindex
+
+if [ $KEEPMODEL = yes ]; then
+  wrapperdir=\$(cat gizawrapper.log | grep 'My tempdir' | head -1 | cut -d' ' -f3)
+  echo "Storing model from \$wrapperdir in \$mydir/model"
+  mkdir model
+  cd \$wrapperdir || die "Could not change dir to \$wrapperdir"
+  cp *.final *.gizacfg vcb* \$mydir/model || die "Failed to copy model files"
+  cd \$mydir || die "Failed to change dir back to \$mydir"
+  echo "Deleting \$wrapperdir"
+  rm -rf \$wrapperdir
+fi
 
 # Standard command footer
 echo Done.
