Added new version of IRSTLM.
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@2314 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/binaries b/playground/eman.seeds/binaries
--- a/playground/eman.seeds/binaries
+++ b/playground/eman.seeds/binaries
@@ -84,9 +84,10 @@ fi
 
 if [ "$SKIP_IRSTLM" != yes ]; then
   echo "Extracting irstlm"
-  tar xzf ../../src/irstlm-5.50.02.tgz || die "Failed to extract srilm"
-  mv irstlm-5.50.02 irstlm || die "Failed to rename dir"
+  tar xzf ../../src/irstlm-5.60.03.tgz || die "Failed to extract srilm"
+  mv irstlm-5.60.03 irstlm || die "Failed to rename dir"
   cd irstlm
+  ./regenerate-makefiles.sh
   ./configure --prefix=\$(pwd) --enable-caching || die "irstlm configure failed"
   make || die "irstlm make failed"
   make install || die "irstlm install failed"
