double check if srilm compiled successfully
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@1607 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/binaries b/playground/eman.seeds/binaries
--- a/playground/eman.seeds/binaries
+++ b/playground/eman.seeds/binaries
@@ -66,6 +66,10 @@ if [ "$SKIP_SRILM" != yes ]; then
   if [ -e lib/i686-gcc4 ] ; then ln -s i686-gcc4 lib/i686; fi
   if [ -e bin/i686-m64 ] ; then ln -s i686-m64 bin/i686; fi
   if [ -e bin/i686-gcc4 ] ; then ln -s i686-gcc4 bin/i686; fi
+
+  [ -e bin/i686/ngram-count ] \
+    || die "ngram-count was not compiled. See \`pwd\`/log* for e.g. this error: '/usr/bin/ld: cannot find -ltcl'"
+
   pwd > ../srilm.path
   
   cd \$mydir || die "Failed to chdir back after srilm"
