avoid a conflict error, there are cases where such a conflict is natural the seed corpus also accepts OUTLINECOUNT=-1, but specify the number of lines   if you can!
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@2979 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/corpus b/playground/eman.seeds/corpus
--- a/playground/eman.seeds/corpus
+++ b/playground/eman.seeds/corpus
@@ -107,8 +107,15 @@ $cmd | gzip -c > corpus.txt.gz \\
 echo "Checking output number of lines of corpus.txt.gz"
 nl=\$(zcat corpus.txt.gz | wc -l)
 
-[ "\$nl" -eq $OUTLINECOUNT ] \\
-|| die "Mismatched number of lines, expected $OUTLINECOUNT, got \$nl"
+if [ $OUTLINECOUNT -eq -1 ]; then
+  echo "Re-registering the corpus with \$nl lines."
+  $PLAYGROUND/corpman register -- corpus.txt.gz -1 $OUTCORP $OUTLANG $OUTFACTS \$nl $DERIVED \\
+    || die "Can't register corpus"
+else
+  # just a check
+  [ "\$nl" -eq $OUTLINECOUNT ] \\
+  || die "Mismatched number of lines, expected $OUTLINECOUNT, got \$nl"
+fi
 
 rm -f \$mydir/../corpman.index || echo "Failed to force reindexing"
 
