sanity checks
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@2781 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/corpus b/playground/eman.seeds/corpus
--- a/playground/eman.seeds/corpus
+++ b/playground/eman.seeds/corpus
@@ -58,6 +58,10 @@ options=0
 [ "$options" -eq 1 ] || die "Bad usage: Needed exactly one of RUN_COMMAND, COMBINE_PARTS and TAKE_FROM_COMMAND, got $options"
 
 if [ ! -z "$RUN_COMMAND" ]; then
+  [ ! -z "$STEPNAME" ] \
+    || die "Please define \$STEPNAME, indicating where the source corpus is."
+  [ -d "../$STEPNAME" ] \
+    || die "The directory with input (../\$STEPNAME) not found"
   inf="../$STEPNAME/$FILENAME"
   # we're not checking -e because the dep may not be done yet
   if [ "$JOBS" == 0 ]; then
