reverting corpus

diff --git a/playground/eman.seeds/corpus b/playground/eman.seeds/corpus
--- a/playground/eman.seeds/corpus
+++ b/playground/eman.seeds/corpus
@@ -45,8 +45,7 @@ SPLIT_TO_SIZE=${SPLIT_TO_SIZE:-30000}
   # even for big corpora, use at most 30k lines per job
 
 # double check our input is a corpus
-STEPPATH=`eman path $STEPNAME`
-[ -z "$STEPPATH" ] || [ -e $STEPPATH/corpman.info ] \
+[ -z "$STEPNAME" ] || [ -e ../$STEPNAME/corpman.info ] \
 || die "\$STEPNAME/corpman.info not found"
 
 # Create corpman info, the last field "1" indicates that this corpus is derived
@@ -64,9 +63,9 @@ options=0
 if [ ! -z "$RUN_COMMAND" ]; then
   [ ! -z "$STEPNAME" ] \
     || die "Please define \$STEPNAME, indicating where the source corpus is."
-  [ -d "$STEPPATH" ] \
-    || die "The directory with input ($STEPPATH) not found"
-  inf="$STEPPATH/$FILENAME"
+  [ -d "../$STEPNAME" ] \
+    || die "The directory with input (../\$STEPNAME) not found"
+  inf="../$STEPNAME/$FILENAME"
   # we're not checking -e because the dep may not be done yet
   if [ "$JOBS" == 0 ]; then
     cmd="zcat $inf \\"$'\n'
