handle remote steps correctly in seed corpus

diff --git a/playground/eman.seeds/corpus b/playground/eman.seeds/corpus
--- a/playground/eman.seeds/corpus
+++ b/playground/eman.seeds/corpus
@@ -45,8 +45,9 @@ SPLIT_TO_SIZE=${SPLIT_TO_SIZE:-30000}
   # even for big corpora, use at most 30k lines per job
 
 # double check our input is a corpus
-[ -z "$STEPNAME" ] || [ -e ../$STEPNAME/corpman.info ] \
-|| die "\$STEPNAME/corpman.info not found"
+STEPPATH=`eman path $STEPNAME`
+[ -z "$STEPPATH" ] || [ -e $STEPPATH/corpman.info ] \
+|| die "\$STEPPATH/corpman.info not found"
 
 # Create corpman info, the last field "1" indicates that this corpus is derived
 # automatically
@@ -61,11 +62,11 @@ options=0
 [ "$options" -eq 1 ] || die "Bad usage: Needed exactly one of RUN_COMMAND, COMBINE_PARTS and TAKE_FROM_COMMAND, got $options"
 
 if [ ! -z "$RUN_COMMAND" ]; then
-  [ ! -z "$STEPNAME" ] \
-    || die "Please define \$STEPNAME, indicating where the source corpus is."
-  [ -d "../$STEPNAME" ] \
-    || die "The directory with input (../\$STEPNAME) not found"
-  inf="../$STEPNAME/$FILENAME"
+  [ ! -z "$STEPPATH" ] \
+    || die "Please define \$STEPPATH, indicating where the source corpus is."
+  [ -d "$STEPPATH" ] \
+    || die "The directory with input (\$STEPPATH) not found"
+  inf="$STEPPATH/$FILENAME"
   # we're not checking -e because the dep may not be done yet
   if [ "$JOBS" == 0 ]; then
     cmd="zcat $inf \\"$'\n'
