Changed data preparation step. Binarization: gunzip first in eman.command because alignment may not be ready during preparation.
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@2752 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/dandata b/playground/eman.seeds/dandata
--- a/playground/eman.seeds/dandata
+++ b/playground/eman.seeds/dandata
@@ -38,17 +38,18 @@ eman defvar SRC help='source language code' \
 perl -e "\$s = $SRC; \$t = $TGT; "'die "Unknown language pair $s-$t" unless("$s-$t" =~ m/^(cs-en|en-cs|de-en|en-de|es-en|en-es|fr-en|en-fr)$/)' || exit 1
 # Select the corpora according to the language pair.
 if   [ "$SRC-$TGT" == "cs-en" ] || [ "$SRC-$TGT" == "en-cs" ] ; then
-  TRAINTM=news-commentary-v6.cs-en+europarl-v6.cs-en
+  export TRAINTM=news-commentary-v6.cs-en+europarl-v6.cs-en
 elif [ "$SRC-$TGT" == "de-en" ] || [ "$SRC-$TGT" == "en-de" ] ; then
-  TRAINTM=news-commentary-v6.de-en+europarl-v6.de-en
+  export TRAINTM=news-commentary-v6.de-en+europarl-v6.de-en
 elif [ "$SRC-$TGT" == "es-en" ] || [ "$SRC-$TGT" == "en-es" ] ; then
-  TRAINTM=news-commentary-v6.es-en+europarl-v6.es-en
+  export TRAINTM=news-commentary-v6.es-en+europarl-v6.es-en
 elif [ "$SRC-$TGT" == "fr-en" ] || [ "$SRC-$TGT" == "en-fr" ] ; then
-  TRAINTM=news-commentary-v6.fr-en+europarl-v6.fr-en
+  export TRAINTM=news-commentary-v6.fr-en+europarl-v6.fr-en
 fi
-TRAINLM=$TRAINTM
-DEV=newstest2008
-TEST=newstest2011
+export TRAINLM=$TRAINTM
+export DEV=newstest2008
+export TEST=newstest2011
+# Old obsolete variables with descriptions for augment.pl
 TRAINALS=$TRAINTM/$SRC+lcstem4
 TRAINALT=$TRAINTM/$TGT+lcstem4
 TRAINTMS=$TRAINTM/$SRC+stc
@@ -59,9 +60,52 @@ DEVT=$DEV/$TGT+stc
 TESTS=$TEST/$SRC+stc
 TESTT=$TEST/$TGT+stc
 # We still use the old augment.pl to fetch the data.
+# (But we may no more need these variables here when augmenting has been isolated into its own steps.)
 AUGMENT=$STATMT/playground/augmented_corpora/augment.pl
 AUGMAKEFILE=$STATMT/playground/augmented_corpora/Makefile
 AUGDIR=/net/work/people/zeman/wmt/augmented_corpora
+# Find steps with prepared links to augmented corpora
+# (so that augment.pl needs not be called again, it takes ages).
+###!!! Make sure that the step exists and that there is just one such step.
+export TRAINALSSTEP=`eman select t augment v ACDESC=\"$TRAINTM/$SRC+lcstem4\"`
+echo   TRAINALSSTEP=$TRAINALSSTEP
+export TRAINALTSTEP=`eman select t augment v ACDESC=\"$TRAINTM/$TGT+lcstem4\"`
+echo   TRAINALTSTEP=$TRAINALTSTEP
+export TRAINTMSSTEP=`eman select t augment v ACDESC=\"$TRAINTM/$SRC+stc\"`
+echo   TRAINTMSSTEP=$TRAINTMSSTEP
+export TRAINTMTSTEP=`eman select t augment v ACDESC=\"$TRAINTM/$TGT+stc\"`
+echo   TRAINTMTSTEP=$TRAINTMTSTEP
+export TRAINLMTSTEP=`eman select t augment v ACDESC=\"$TRAINTM/$TGT+stc\"`
+echo   TRAINLMTSTEP=$TRAINLMTSTEP
+export DEVSSTEP=`eman select t augment v ACDESC=\"$DEV/$SRC+stc\"`
+echo   DEVSSTEP=$DEVSSTEP
+export DEVTSTEP=`eman select t augment v ACDESC=\"$DEV/$TGT+stc\"`
+echo   DEVTSTEP=$DEVTSTEP
+export TESTSSTEP=`eman select t augment v ACDESC=\"$TEST/$SRC+stc\"`
+echo   TESTSSTEP=$TESTSSTEP
+export TESTTSTEP=`eman select t augment v ACDESC=\"$TEST/$TGT+stc\"`
+echo   TESTTSTEP=$TESTTSTEP
+eman \
+  defvar TRAINALSSTEP type=reqstep help="where is training/$SRC+lcstem4" \
+  defvar TRAINALTSTEP type=reqstep help="where is training/$TGT+lcstem4" \
+  defvar TRAINTMSSTEP type=reqstep help="where is training/$SRC+stc" \
+  defvar TRAINTMTSTEP type=reqstep help="where is training/$TGT+stc" \
+  defvar TRAINLMTSTEP type=reqstep help="where is training/$TGT+stc" \
+  defvar DEVSSTEP     type=reqstep help="where is dev/$SRC+stc" \
+  defvar DEVTSTEP     type=reqstep help="where is dev/$TGT+stc" \
+  defvar TESTSSTEP    type=reqstep help="where is test/$SRC+stc" \
+  defvar TESTTSTEP    type=reqstep help="where is test/$TGT+stc" \
+|| exit 1
+# convert the dependencies to absolute paths
+TRAINALSSTEPDIR=`eman path $TRAINALSSTEP`
+TRAINALTSTEPDIR=`eman path $TRAINALTSTEP`
+TRAINTMSSTEPDIR=`eman path $TRAINTMSSTEP`
+TRAINTMTSTEPDIR=`eman path $TRAINTMTSTEP`
+TRAINLMTSTEPDIR=`eman path $TRAINLMTSTEP`
+DEVSSTEPDIR=`eman path $DEVSSTEP`
+DEVTSTEPDIR=`eman path $DEVTSTEP`
+TESTSSTEPDIR=`eman path $TESTSSTEP`
+TESTTSTEPDIR=`eman path $TESTTSTEP`
 
 # Set local bash variables.
 eval `eman bash-loadvars`
@@ -84,25 +128,22 @@ set -o pipefail
 function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }
 renice 10 \$\$
 
-# Note: the essential --dir and --makefile arguments must be stored in a file
-# because augment.pl may call "make" and the Makefile will call another
-# augment.pl, without being able to put through these arguments.
-echo "--dir=$AUGDIR --makefile=$AUGMAKEFILE" > $STATMT/playground/augmented_corpora/augment.pl.flags || die "Failed to save augment.pl.flags"
-ln -s \`$AUGMENT $TRAINALS\` trainal.$SRC.gz || die "Failed to link to $TRAINALS"
-ln -s \`$AUGMENT $TRAINALT\` trainal.$TGT.gz || die "Failed to link to $TRAINALT"
-ln -s \`$AUGMENT $TRAINTMS\` train.$SRC.gz   || die "Failed to link to $TRAINTMS"
-ln -s \`$AUGMENT $TRAINTMT\` train.$TGT.gz   || die "Failed to link to $TRAINTMT"
-ln -s \`$AUGMENT $TRAINLMT\` trainlm.$TGT.gz || die "Failed to link to $TRAINLMT"
-ln -s \`$AUGMENT $DEVS\` dev.$SRC.gz         || die "Failed to link to $DEVS"
-ln -s \`$AUGMENT $DEVT\` dev.$TGT.gz         || die "Failed to link to $DEVT"
-ln -s \`$AUGMENT $TESTS\` test.$SRC.gz       || die "Failed to link to $TESTS"
-ln -s \`$AUGMENT $TESTT\` test.$TGT.gz       || die "Failed to link to $TESTT"
+ln -s $TRAINALSSTEPDIR/corpus.gz trainal.$SRC.gz || die "Failed to link to source alignment training file"
+ln -s $TRAINALTSTEPDIR/corpus.gz trainal.$TGT.gz || die "Failed to link to target alignment training file"
+ln -s $TRAINTMSSTEPDIR/corpus.gz train.$SRC.gz   || die "Failed to link to source training file"
+ln -s $TRAINTMTSTEPDIR/corpus.gz train.$TGT.gz   || die "Failed to link to target training file"
+ln -s $TRAINLMTSTEPDIR/corpus.gz trainlm.$TGT.gz || die "Failed to link to target language model training file"
+ln -s $DEVSSTEPDIR/corpus.gz dev.$SRC.gz         || die "Failed to link to source development file"
+ln -s $DEVTSTEPDIR/corpus.gz dev.$TGT.gz         || die "Failed to link to target development file"
+ln -s $TESTSSTEPDIR/corpus.gz test.$SRC.gz       || die "Failed to link to source test file"
+ln -s $TESTTSTEPDIR/corpus.gz test.$TGT.gz       || die "Failed to link to target test file"
 # Clean training data and alignment of sentences of 100 or more words.
 # Longer sentences sometimes make binarization fail.
 $SCRIPTS/clean-corpus-dan.pl -min 1 -max 99 trainal.$SRC.gz trainal.$TGT.gz train.$SRC.gz train.$TGT.gz \\
 || die "Cannot clean corpus from empty or too long sentences"
 for i in trainal.$SRC trainal.$TGT train.$SRC train.$TGT ; do
-  mv $i.clean.gz $i.gz || die "Failed mv $i.clean.gz $i.gz"
+  rm -f \$i.gz           || die "Failed rm \$i.gz"
+  mv \$i.clean.gz \$i.gz || die "Failed mv \$i.clean.gz \$i.gz"
 done
 
 # Standard command footer
