split mert into steps mert, translate, eval(uator)
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@2788 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/eval b/playground/eman.seeds/eval
--- a/playground/eman.seeds/eval
+++ b/playground/eman.seeds/eval
@@ -1,118 +1,27 @@
 #!/bin/bash
 
-if [ -z "$MERTSTEP" ] \
-|| [ -z "$TESTCORP" ]; then
-  echo "You must set: "
-  echo "  \$BINARIES to the step containing compiled tools (inheritable from mertstep"
-  echo "  \$MERTSTEP to the directory that contains the model, incl. all files, the optimized ini will be used"
-  echo "  \$TESTCORP to the corpus for evaluation"
-  echo "and optionally"
-  echo "  \$REFAUG to override reference annotation used during mert"
-  echo "  \$MOSESFLAGS to any further flags"
-  echo "  \$GRIDFLAGS to any further flags"
-  echo "  \$JOBS to number of jobs or 0 for serial"
-  echo "  \$ITER to the ITER-th BEST at... (will use run(ITER+1).moses.ini)"
-  exit 1
-fi
+set -o pipefail
+function die() { echo "$@" | tee FAILED >&2; exit 1 ; }
 
-[[ -d ../s.mert.$MERTSTEP ]] && MERTSTEP=s.mert.$MERTSTEP
+PLAYGROUND=$(eman path)
 
-if [[ ! -d ../$MERTSTEP ]]; then
-  echo "Experiment not found: $MERTSTEP"
-  exit 1
-fi
+# Ensure all the required variables are set (or provide the default)
+eman \
+  defvar TRANSSTEP type=optstep default='' \
+    help="translation step, implies corpora and factor if given" \
+  defvar MOSESSTEP type=reqstep inherit=TRANSSTEP \
+    help="the step containing compiled tools" \
+  defvar TESTCORP inherit=TRANSSTEP help="the translated corpus" \
+  defvar TRANSAUG inherit=TRANSSTEP:UNTOKAUG help="translation language+factors" \
+  defvar REFAUG inherit=TRANSSTEP \
+    help="reference language+factors" \
+|| exit 1
 
-# load inherited/inheritable binaries and gridflags
-INHER_BINARIES=`cat ../$MERTSTEP/eman.vars | grep ^BINARIES | cut -d= -f2-`
-INHER_GRIDFLAGS=`cat ../$MERTSTEP/eman.vars | grep ^GRIDFLAGS | cut -d= -f2- | sed 's/^"//; s/"$//'`
-
-[ -z "$GRIDFLAGS" ] && GRIDFLAGS=$INHER_GRIDFLAGS
-
-JOBS=${JOBS:-10}
-
-if [ ! -z "$ITER" ]; then
-  iterprefix=run$(($ITER+1)).
-  itertag=ITER$ITER
-fi
-
-echo `cat ../$MERTSTEP/eman.tag`"$itertag"TEST$TESTCORP > eman.tag
-
-if [ -z "$REFAUG" ]; then
-  eval `cat ../$MERTSTEP/eman.vars | grep 'REFAUG='`
-  echo "Inheriting REFAUG: $REFAUG"
-fi
-
-MODELEXP=`cat ../$MERTSTEP/info.modelexp`
-SAVEMODELEXP=$MODELEXP
-eval `cat ../$MODELEXP/eman.vars` || exit 1
-MODELEXP=$SAVEMODELEXP
-cat << KONEC > eman.vars
-BINARIES=$BINARIES
-MERTSTEP=$MERTSTEP
-TESTCORP=$TESTCORP
-REFAUG=$REFAUG
-MOSESFLAGS="$MOSESFLAGS"
-GRIDFLAGS="$GRIDFLAGS"
-JOBS=$JOBS
-ITER=$ITER
-KONEC
-echo $MODELEXP > ./info.modelexp
-echo $MERTSTEP > info.mertstep
-
-echo $MERTSTEP > ./eman.deps
-
-if [ -z "$BINARIES" ] || [ "$INHER_BINARIES" == "$BINARIES" ]; then
-  # inherit binarie
-  BINARIES=$INHER_BINARIES
-  # inherited binaries don't belong to our dependencies, we
-  # hope our predecessor has them as a dependence
-else
-  # put BINARIES to our deps as well
-  echo $BINARIES >> eman.deps
-fi
-
-SCRIPTS_ROOTDIR="`cat ../$BINARIES/scripts.rootdir`"
-MOSESCMD="`pwd`/../$BINARIES/bin/moses"
-
+# Set local bash variables
+eval `eman bash-loadvars`
 
 # Stop here if we are just initing ourselves
 [ -z "$INIT_ONLY" ] || exit 0
-
-# clone some importnant executables
-../../scripts/wiseln $MOSESCMD ./moses || exit 1
-../../scripts/wiseln ../$MERTSTEP/testbleu ./testbleu || exit 1
-
-## We're using irstlm, change the lmodel-file type:
-# ../set_lm_type.pl ./moses.ini || die "Failed to set lmtype" || exit 1
-
-../augmented_corpora/augment.pl --dump $TESTCORP/$SRCAUG > evaluation.in || exit 1
-../augmented_corpora/augment.pl --dump $TESTCORP/$REFAUG > evaluation.ref.0 || exit 1
-
-echo Checking eval corp size
-[ `wc -l < evaluation.in` -gt 0 ] || exit 1
-[ `wc -l < evaluation.in` == `wc -l < evaluation.ref.0` ] || exit 1
-
-TARGETLAN_FOR_DETOKENIZER=`echo $REFAUG | sed 's/^\(..\).*/\1/'`
-if ! echo "test" | $SCRIPTS_ROOTDIR/tokenizer/detokenizer.perl \
-       -u -l $TARGETLAN_FOR_DETOKENIZER > /dev/null 2>&1 ; then 
-  echo "Defaulting to 'en' as the targetlang for detokenizer."
-  TARGETLAN_FOR_DETOKENIZER=en
-fi
-
-
-# for running this command, qsub is allowed, although we're going to submit jobs ourselves
-# echo "no" > qsub-allowed
-
-MOSESPARALLEL="\$SCRIPTS_ROOTDIR/generic/moses-parallel.pl"
-
-if [ $JOBS == 0 ]; then
-  GRIDARGS=""
-  MOSESPARALLELIZER=""
-else
-  GRIDARGS="--jobs=$JOBS --queue-parameters=' $GRIDFLAGS -p -200 -cwd -S /bin/bash ' -feed-decoder-via-stdin "
-  MOSESPARALLELIZER="$MOSESPARALLEL $GRIDARGS -decoder "
-fi
-
 
 cat << KONEC > eman.command
 # This is the command to be run here
@@ -121,57 +30,48 @@ echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
 echo "== Hostname:  "\`hostname\`
 echo "== Directory: "\`pwd\`
 echo "=============================="
-renice 10 \$\$
-
-mydir=\`pwd\`
-
-# init grid environment
-. /net/projects/SGE/user/sge_profile
-
+mydir=\$(pwd)
 set -o pipefail
-function die() { echo "\$@" | tee FAILED >&2; exit 1 ; }
+function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }
+renice 10 \$\$
+ulimit -c 1 # core files limited to 1 byte
 
-export SCRIPTS_ROOTDIR=$SCRIPTS_ROOTDIR
-echo export SCRIPTS_ROOTDIR=$SCRIPTS_ROOTDIR
+MERTSTEPDIR=\`eman path $MERTSTEP \`
+MOSESSTEPDIR=\`eman path $MOSESSTEP \`
 
-## Clone the moses.ini and source files
-\$SCRIPTS_ROOTDIR/training/clone_moses_model.pl \\
-  --symlink \\
-  ../$MERTSTEP/mert-tuning/"$iterprefix"moses.ini || die "Failed to clone"
+gunzip $PLAYGROUND/../src/testbleu.gz -c > ./testbleu \
+|| die "Cannot extract testbleu binary!"
+chmod +x ./testbleu
 
-\$SCRIPTS_ROOTDIR/training/absolutize_moses_model.pl ./moses.ini > moses.abs.ini || die "Failed to absolutize"
+EVALUATOR=\$MOSESSTEPDIR/moses/mert/evaluator
+[ -x \$EVALUATOR ] || die "Missing: \$EVALUATOR"
 
-\$SCRIPTS_ROOTDIR/training/filter-model-given-input.pl filtered-for-eval ./moses.abs.ini evaluation.in || die "Failed to filter"
+function mkcorpus() {
+  $PLAYGROUND/corpman --wait \$1 || die "Failed to prepare \$1"
+  step_file_col=(\$($PLAYGROUND/corpman \$1))
+  if [ "\${step_file_col[2]}" == "-1" ]; then
+    $PLAYGROUND/../scripts/wiseln $PLAYGROUND/\${step_file_col[0]}/\${step_file_col[1]} \\
+      corpus.\$2.gz \
+    || die "Failed to clone \$2 corpus \$1"
+  else
+    echo "Selecting the column from \$step_file_col"
+    eval \$($PLAYGROUND/corpman --cmd \$1) \\
+    | gzip -c > corpus.\$2.gz
+  fi
+}
 
-$MOSESPARALLELIZER \\
-  ./moses \\
-  $MOSESFLAGS \\
-  -input-file ./evaluation.in \\
-  -alignment-output-file ./evaluation.opt.ali \\
-  -config ./filtered-for-eval/moses.ini \\
-  > evaluation.opt.out \\
-   || die "Failed to translate"
+mkcorpus $TESTCORP/$TRANSAUG translation
+gunzip corpus.translation.gz
 
-echo "Detokenizing evaluation.opt.out"
-\$SCRIPTS_ROOTDIR/tokenizer/detokenizer.perl -u -l $TARGETLAN_FOR_DETOKENIZER \\
-< evaluation.opt.out > evaluation.opt.txt \\
-  || die "Failed to detokenize"
+mkcorpus $TESTCORP/$REFAUG reference
+gunzip corpus.reference.gz
 
-echo "Tuned BLEU:"
-#\$SCRIPTS_ROOTDIR/generic/multi-bleu.perl evaluation.ref. < evaluation.opt.out | tee BLEU.opt
-./testbleu evaluation.ref.0 < evaluation.opt.out | tee BLEU.opt \\
-  || die "Failed to eval BLEU"
+./testbleu corpus.reference < corpus.translation | tee BLEU
+|| die "evaluator exit code is not 0"
 
-echo "You could prepare detailed output for manual inpection:"
-echo ./moses -input-file ./evaluation.in -config ./filtered-for-eval-opt/moses.ini \\
-  -verbose 3 \\
-  2>&1
-#  | skipbetween '^Translation Option Collection' '^total hypotheses generated' \\
-#  | head -c 300k \\
-#  > evaluation.opt.verbose
-
-echo DONE > \$mydir/eman.status
-
+# Standard command footer
+echo Done.
+eman succeed \$mydir
 echo "=============================="
 echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
 echo "== Hostname:  "\`hostname\`
diff --git a/playground/eman.seeds/evaluator b/playground/eman.seeds/evaluator
--- a/playground/eman.seeds/evaluator
+++ b/playground/eman.seeds/evaluator
@@ -3,20 +3,24 @@
 set -o pipefail
 function die() { echo "$@" | tee FAILED >&2; exit 1 ; }
 
+PLAYGROUND=$(eman path)
+
 # Ensure all the required variables are set (or provide the default)
 eman \
-    defvar MERTSTEP type=reqstep \
-        help="step containing untokenized candidate (evaluation.opt.out) and references (evaluation.ref.*)" \
-    defvar MOSESSTEP type=reqstep inherit=MERTSTEP:BINARIES \
-        help="the step containing compiled tools; inherited from MERTSTEP" \
-    defvar SCORERS default="BLEU;PER;TER;CDER" \
-        help="scorers you want to use" \
+  defvar SCORERS default="BLEU;PER;TER;CDER" \
+    help="scorers you want to use" \
+  defvar TRANSSTEP type=optstep default='' \
+    help="translation step, implies corpora and factor if given" \
+  defvar MOSESSTEP type=reqstep inherit=TRANSSTEP \
+    help="the step containing compiled tools" \
+  defvar TESTCORP inherit=TRANSSTEP help="the translated corpus" \
+  defvar TRANSAUG inherit=TRANSSTEP:UNTOKAUG help="translation language+factors" \
+  defvar REFAUGS inherit=TRANSSTEP:REFAUG \
+    help="reference language+factors; use ';' to delimit multiple references" \
 || exit 1
 
 # Set local bash variables
 eval `eman bash-loadvars`
-
-#eman add-tag `eman tag $MERTSTEP`
 
 # Stop here if we are just initing ourselves
 [ -z "$INIT_ONLY" ] || exit 0
@@ -34,14 +38,41 @@ function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }
 renice 10 \$\$
 ulimit -c 1 # core files limited to 1 byte
 
-MERTSTEP=\`eman path $MERTSTEP \`
-MOSESSTEP=\`eman path $MOSESSTEP \`
+MERTSTEPDIR=\`eman path $MERTSTEP \`
+MOSESSTEPDIR=\`eman path $MOSESSTEP \`
 
-EVALUATOR=\$MOSESSTEP/moses/mert/evaluator
+EVALUATOR=\$MOSESSTEPDIR/moses/mert/evaluator
 [ -x \$EVALUATOR ] || die "Missing: \$EVALUATOR"
 
-REFERENCES=\`ls -1 \$MERTSTEP/evaluation.ref* | grep "/evaluation\.ref\.[0-9]$" | tr "\\n" "," | head -c -1\`
-CANDIDATE=\$MERTSTEP/evaluation.opt.out
+function mkcorpus() {
+  $PLAYGROUND/corpman --wait \$1 || die "Failed to prepare \$1"
+  step_file_col=(\$($PLAYGROUND/corpman \$1))
+  if [ "\${step_file_col[2]}" == "-1" ]; then
+    $PLAYGROUND/../scripts/wiseln $PLAYGROUND/\${step_file_col[0]}/\${step_file_col[1]} \\
+      corpus.\$2.gz \
+    || die "Failed to clone \$2 corpus \$1"
+  else
+    echo "Selecting the column from \$step_file_col"
+    eval \$($PLAYGROUND/corpman --cmd \$1) \\
+    | gzip -c > corpus.\$2.gz
+  fi
+}
+
+mkcorpus $TESTCORP/$TRANSAUG translation
+gunzip corpus.translation.gz
+
+REFAUGS=`echo "$REFAUGS" | tr ';' ' '`
+REFERENCES=''
+idx=0
+for i in \$REFAUGS; do
+  mkcorpus $TESTCORP/\$i reference.\$idx
+  gunzip corpus.reference.\$idx.gz
+  REFERENCES="\$REFERENCES,corpus.reference.\$idx"
+  idx=\$((\$idx + 1))
+done
+
+REFERENCES=\`echo \$REFERENCES | sed 's/^,//'\`
+CANDIDATE=corpus.translation
 
 \$EVALUATOR \\
     --sctype "$SCORERS" \\
diff --git a/playground/eman.seeds/translate b/playground/eman.seeds/translate
--- a/playground/eman.seeds/translate
+++ b/playground/eman.seeds/translate
@@ -1,32 +1,30 @@
 #!/bin/bash
-# just translates the given corpus, no reference to evaluate against
+# translates the given corpus
 
-## Save our own copy of moses
+PLAYGROUND=$(eman path)
 
-if [ -z "$MERTEXP" ] \
-|| [ -z "$BINARIES" ] \
-|| [ -z "$TESTCORP" ]; then
-  echo "You must set: "
-  echo "  \$BINARIES to the step containing compiled tools"
-  echo "  \$MERTEXP to the directory that contains the model, incl. all files, the optimized ini will be used"
-  echo "  \$TESTCORP to the corpus for evaluation"
-  echo "and optionally"
-  echo "  \$MOSESFLAGS to any further flags"
-  echo "  \$GRIDFLAGS to any further flags"
-  echo "  \$JOBS to number of jobs or 0 for serial"
-  echo "  \$ITER to the ITER-th BEST at... (will use run(ITER+1).moses.ini)"
-  exit 1
-fi
+eman \
+  defvar MERTSTEP type=reqstep \
+    help="step containing configuration file for Moses" \
+  defvar MOSESSTEP type=reqstep inherit=MERTSTEP \
+    help="the step containing compiled tools; inherited from MERTSTEP" \
+  defvar TESTCORP help='the corpus to translate' \
+  defvar SRCAUG inherit=MERTSTEP \
+    help="language+factors to translate" \
+  defvar REFAUG inherit=MERTSTEP \
+    help="language that will be created by translating; factor is 'untok'" \
+  defvar ITER default='' \
+    help="which MERT iteration weights to use; default is the final set" \
+  defvar SEARCH default=cube help='the search type (beam or cube)' \
+|| exit 1
 
-SCRIPTS_ROOTDIR="`cat ../$BINARIES/scripts.rootdir`"
-MOSESCMD="`pwd`/../$BINARIES/bin/moses"
+eval `eman bash-loadvars`
 
-[[ -d ../exp.mert.$MERTEXP ]] && MERTEXP=exp.mert.$MERTEXP
-
-if [[ ! -d ../$MERTEXP ]]; then
-  echo "Experiment not found: $MERTEXP"
-  exit 1
-fi
+STEPNAME=$(basename $(pwd))
+MOSESSTEPDIR=$(eman path $MOSESSTEP)
+MERTSTEPDIR=$(eman path $MERTSTEP)
+MOSESCMD="$MOSESSTEPDIR/bin/moses"
+SCRIPTS_ROOTDIR="$MOSESSTEPDIR/moses/scripts/"
 
 JOBS=${JOBS:-10}
 
@@ -35,58 +33,62 @@ if [ ! -z "$ITER" ]; then
   itertag=ITER$ITER
 fi
 
-echo `cat ../$MERTEXP/eman.tag`"$itertag"TEST$TESTCORP > eman.tag
+MERTTAG=$(eman tag $MERTSTEP | cut -f2 | sed 's/ *//g')
+eman add-tag "$MERTTAG""$itertag"TEST$TESTCORP .
 
-if [ -z "$REFAUG" ]; then
-  eval `cat ../$MERTEXP/eman.vars | grep 'REFAUG='`
-  echo "Inheriting REFAUG: $REFAUG"
-fi
+case "$SEARCH" in
+beam)
+  SEARCHFLAG="-search-algorithm 0"
+  ;;
+cube)
+  SEARCHFLAG="-search-algorithm 1"
+  ;;
+*)
+  die "Bad search algorithm: $SEARCH"
+  ;;
+esac
 
-MODELEXP=`cat ../$MERTEXP/info.modelexp`
-SAVEMODELEXP=$MODELEXP
-eval `cat ../$MODELEXP/eman.vars` || exit 1
-MODELEXP=$SAVEMODELEXP
-cat << KONEC > eman.vars
-BINARIES=$BINARIES
-MERTEXP=$MERTEXP
-TESTCORP=$TESTCORP
-MOSESFLAGS="$MOSESFLAGS"
-GRIDFLAGS="$GRIDFLAGS"
-JOBS=$JOBS
-ITER=$ITER
-KONEC
-echo $MODELEXP > ./info.modelexp
-echo $MERTEXP > info.mertexp
+# ask for corpus to translate, add it to deps
+srccorpstep=$($PLAYGROUND/corpman --init $TESTCORP/$SRCAUG | cut -f1)
+[ ! -z "$srccorpstep" ] || die "Missing source corpus"
 
-echo $MERTEXP > ./eman.deps
-echo $BINARIES >> eman.deps
+eman add-deps . $srccorpstep $tgtcorpstep
+
+OUTLANG=`echo $REFAUG | cut -d'+' -f1`
+UNTOKFACT="$STEPNAME-untok"
+TOKFACT="$STEPNAME-$(echo $REFAUG | cut -d'+' -f2-)"
+ALIFACT="$STEPNAME-ali"
+
+UNTOKAUG="$OUTLANG+$UNTOKFACT" eman defvar UNTOKAUG
+TOKAUG="$OUTLANG+$TOKFACT" eman defvar TOKAUG
+OUTALIAUG="$OUTLANG+$ALIFACT" eman defvar OUTALIAUG
+
+# promise translated corpus 
+# linecount is added after tranlating
+$PLAYGROUND/corpman register -- translated.gz \
+  -1 $TESTCORP $OUTLANG $TOKFACT -1 0 \
+|| die "Can't register corpus"
+$PLAYGROUND/corpman register -- translated.untok.gz \
+  -1 $TESTCORP $OUTLANG $UNTOKFACT -1 0 \
+|| die "Can't register corpus"
+$PLAYGROUND/corpman register -- alignment.gz \
+  -1 $TESTCORP $OUTLANG $ALIFACT -1 0 \
+|| die "Can't register corpus"
 
 # Stop here if we are just initing ourselves
 [ -z "$INIT_ONLY" ] || exit 0
 
 # clone some importnant executables
-../../scripts/wiseln $MOSESCMD ./moses || exit 1
-
-## We're using irstlm, change the lmodel-file type:
-# ../set_lm_type.pl ./moses.ini || die "Failed to set lmtype" || exit 1
-
-../augmented_corpora/augment.pl --dump $TESTCORP/$SRCAUG > evaluation.in || exit 1
-
-echo Checking eval corp size
-[ `wc -l < evaluation.in` -gt 0 ] || exit 1
+$PLAYGROUND/../scripts/wiseln $MOSESCMD ./moses || exit 1
 
 TARGETLAN_FOR_DETOKENIZER=`echo $REFAUG | sed 's/^\(..\).*/\1/'`
-if ! echo "test" | $SCRIPTS_ROOTDIR/recaser/detokenizer.perl \
+if ! echo "test" | $SCRIPTS_ROOTDIR/tokenizer/detokenizer.perl \
        -u -l $TARGETLAN_FOR_DETOKENIZER > /dev/null 2>&1 ; then 
   echo "Defaulting to 'en' as the targetlang for detokenizer."
   TARGETLAN_FOR_DETOKENIZER=en
 fi
 
-
-# for running this command, qsub is allowed, although we're going to submit jobs ourselves
-# echo "no" > qsub-allowed
-
-MOSESPARALLEL="\$SCRIPTS_ROOTDIR/generic/moses-parallel.pl"
+MOSESPARALLEL="$SCRIPTS_ROOTDIR/generic/moses-parallel.pl"
 
 if [ $JOBS == 0 ]; then
   GRIDARGS=""
@@ -95,7 +97,6 @@ else
   GRIDARGS="--jobs=$JOBS --queue-parameters=' $GRIDFLAGS -p -200 -cwd -S /bin/bash ' -feed-decoder-via-stdin "
   MOSESPARALLELIZER="$MOSESPARALLEL $GRIDARGS -decoder "
 fi
-
 
 cat << KONEC > eman.command
 # This is the command to be run here
@@ -117,38 +118,70 @@ function die() { echo "\$@" | tee FAILED >&2; exit 1 ; }
 export SCRIPTS_ROOTDIR=$SCRIPTS_ROOTDIR
 echo export SCRIPTS_ROOTDIR=$SCRIPTS_ROOTDIR
 
+function mkcorpus() {
+  $PLAYGROUND/corpman --wait \$1 || die "Failed to prepare \$1"
+  step_file_col=(\$($PLAYGROUND/corpman \$1))
+  if [ "\${step_file_col[2]}" == "-1" ]; then
+    $PLAYGROUND/../scripts/wiseln $PLAYGROUND/\${step_file_col[0]}/\${step_file_col[1]} \\
+      corpus.\$2.gz \
+    || die "Failed to clone \$2 corpus \$1"
+  else
+    echo "Selecting the column from \$step_file_col"
+    eval \$($PLAYGROUND/corpman --cmd \$1) \\
+    | gzip -c > corpus.\$2.gz
+  fi
+}
+
+mkcorpus $TESTCORP/$SRCAUG src
+gunzip corpus.src.gz
+
 ## Clone the moses.ini and source files
 \$SCRIPTS_ROOTDIR/training/clone_moses_model.pl \\
   --symlink \\
-  ../$MERTEXP/mert-tuning/"$iterprefix"moses.ini || die "Failed to clone"
+  $MERTSTEPDIR/mert-tuning/"$iterprefix"moses.ini || die "Failed to clone"
 
 \$SCRIPTS_ROOTDIR/training/absolutize_moses_model.pl ./moses.ini > moses.abs.ini || die "Failed to absolutize"
 
-\$SCRIPTS_ROOTDIR/training/filter-model-given-input.pl filtered-for-eval ./moses.abs.ini evaluation.in || die "Failed to filter"
+\$SCRIPTS_ROOTDIR/training/filter-model-given-input.pl filtered-for-eval ./moses.abs.ini corpus.src || die "Failed to filter"
 
 $MOSESPARALLELIZER \\
   ./moses \\
-  $MOSESFLAGS \\
-  -input-file ./evaluation.in \\
+  $SEARCHFLAGS \\
+  -input-file ./corpus.src \\
+  -alignment-output-file ./alignment \
   -config ./filtered-for-eval/moses.ini \\
 | gzip -c \\
-> evaluation.opt.out.gz \\
+> translated.gz \\
 || die "Failed to translate"
 
-echo "Detokenizing evaluation.opt.out"
-zcat evaluation.opt.out.gz \\
-| \$SCRIPTS_ROOTDIR/recaser/detokenizer.perl -u -l $TARGETLAN_FOR_DETOKENIZER \\
+gzip alignment
+
+echo "Detokenizing translation"
+zcat translated.gz \\
+| \$SCRIPTS_ROOTDIR/tokenizer/detokenizer.perl -u -l $TARGETLAN_FOR_DETOKENIZER \\
 | gzip -c \\
-> evaluation.opt.txt.gz \\
-  || die "Failed to detokenize"
+> translated.untok.gz \\
+|| die "Failed to detokenize"
+
+linecount=\`zcat translated.untok.gz | wc -l\`
+## fill in linecount of the final corpus
+$PLAYGROUND/corpman register -- translated.gz \
+  -1 $TESTCORP $OUTLANG $TOKFACT \$linecount 0 \
+|| die "Can't register linecount of the translated corpus"
+$PLAYGROUND/corpman register -- translated.untok.gz \
+  -1 $TESTCORP $OUTLANG $UNTOKFACT \$linecount 0 \
+|| die "Can't register linecount of the translated corpus"
+$PLAYGROUND/corpman register -- alignment.gz \
+  -1 $TESTCORP $OUTLANG $ALIFACT \$linecount 0 \
+|| die "Can't register linecount of the output alignment"
 
 echo "You could prepare detailed output for manual inpection:"
-echo ./moses -input-file ./evaluation.in -config ./filtered-for-eval-opt/moses.ini \\
+echo ./moses -input-file ./corpus.src -config ./filtered-for-eval-opt/moses.ini \\
   -verbose 3 \\
   2>&1
 #  | skipbetween '^Translation Option Collection' '^total hypotheses generated' \\
 #  | head -c 300k \\
-#  > evaluation.opt.verbose
+#  > translated.verbose
 
 echo DONE > \$mydir/eman.status
 
