updating falign to use the new symmetrization tool

diff --git a/playground/eman.seeds/falign b/playground/eman.seeds/falign
--- a/playground/eman.seeds/falign
+++ b/playground/eman.seeds/falign
@@ -96,6 +96,10 @@ function mkcorpus() {
     fi
   fi
 }
+
+cd $PLAYGROUND/tools/symmetrize && make && cd \$mydir || die "Failed to compile alignment symmetrization"
+wiseln $PLAYGROUND/tools/symmetrize/symmetrize symmetrize
+
 mkcorpus $CORPUS/$SRCALIAUG src
 mkcorpus $CORPUS/$TGTALIAUG tgt
 
@@ -117,7 +121,7 @@ wait
 
 # symmetrize, TODO other symmetrizations
 echo "Started symmetrization at "\`date '+%Y%m%d-%H%M'\`
-paste align.left align.right | $PLAYGROUND/tools/symmetrize.py gd fa \
+./symmetrize align.left align.right g+d+fa \
   | gzip -c > alignment.gz || die "Failed to symmetrize"
 
 # Standard command footer
