check for SRILM only in prepare, not in init (binaries may not be done yet)
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@1570 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/lm b/playground/eman.seeds/lm
--- a/playground/eman.seeds/lm
+++ b/playground/eman.seeds/lm
@@ -21,11 +21,6 @@ fi
 
 BINDIR="`pwd`../$BINARIES/bin/"
 
-if [ ! -f ../$BINARIES/srilm.path ]; then
-  echo "SRILM not found in $BINARIES"
-  exit 1
-fi
-
 SRILMDIR1="`cat ../$BINARIES/srilm.path`/bin/"
 SRILMDIR2="`cat ../$BINARIES/srilm.path`/bin/i686/"
 
@@ -64,6 +59,13 @@ echo $BINARIES > eman.deps
 
 # Stop here if we are just initing ourselves
 [ -z "$INIT_ONLY" ] || exit 0
+
+
+if [ ! -f ../$BINARIES/srilm.path ]; then
+  echo "SRILM not found in $BINARIES"
+  exit 1
+fi
+
 
 # Run checks in the preparation phase
 [ -d ../augmented_corpora/$CORP ] || die "Can't find corpus $CORP"
