lm now calls corpman just once corpman saves its index when it has inited new corpora
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@2903 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/lm b/playground/eman.seeds/lm
--- a/playground/eman.seeds/lm
+++ b/playground/eman.seeds/lm
@@ -71,15 +71,19 @@ echo "Using this make-big-lm:"
 which make-big-lm || die "No make-big-lm"
 
 function mkcorpus() {
-  $PLAYGROUND/corpman --wait \$1 || die "Failed to prepare \$1"
-  step_file_col=(\$($PLAYGROUND/corpman \$1))
+  corpspec=\$($PLAYGROUND/corpman --wait \$1)
+  echo "corpman for \$1 returned: \$corpspec" # for the logfile
+  step_file_col=(\$corpspec)
+  corpfile="$PLAYGROUND/\${step_file_col[0]}/\${step_file_col[1]}"
+  [ -e \$corpfile ] \\
+    || die "Failed to prepare \$1, corpus file not found: \$corpfile"
   if [ "\${step_file_col[2]}" == "-1" ]; then
-    $PLAYGROUND/../scripts/wiseln $PLAYGROUND/\${step_file_col[0]}/\${step_file_col[1]} \\
+    $PLAYGROUND/../scripts/wiseln \$corpfile \\
       corpus.\$2.gz \
     || die "Failed to clone \$2 corpus \$1"
   else
-    echo "Selecting the column from \$step_file_col"
-    eval \$($PLAYGROUND/corpman --cmd \$1) \\
+    echo "Selecting the column \${step_file_col[2]} from \$corpfile"
+    zcat \$corpfile | cut -f "\${step_file_col[2]}" \\
     | gzip -c > corpus.\$2.gz
   fi
 }
