gzipping LM after creation
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@3542 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/lm b/playground/eman.seeds/lm
--- a/playground/eman.seeds/lm
+++ b/playground/eman.seeds/lm
@@ -138,6 +138,9 @@ else
   rm -rf \$partstempdir
 fi
 
+echo Gzipping corpus.lm
+gzip corpus.lm || die "Failed to gzip"
+
 # Standard command footer
 echo Done.
 eman succeed \$mydir
