fixing eman seed lm
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@1457 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/lm b/playground/eman.seeds/lm
--- a/playground/eman.seeds/lm
+++ b/playground/eman.seeds/lm
@@ -4,18 +4,12 @@ function die() { echo "$@" | tee FAILED >&2; exit 1 ; }
 
 set -o pipefail
 
-if [ -z "$BINARIES" ]; then
-  echo "Set \$BINARIES to the step containing compiled tools"
-  exit 1
-fi
-
-SCRIPTS_ROOTDIR="`cat ../$BINARIES/scripts.rootdir`"
-BINDIR="`pwd`../$BINARIES/bin/"
-
 if [ -z "$CORP" ] \
 || [ -z "$CORPAUG" ] \
+|| [ -z "$BINARIES" ] \
 || [ -z "$ORDER" ]; then
   echo "You must set: "
+  echo "  \$BINARIES to the step containing compiled tools"
   echo "  \$CORP to the shortname of corpus"
   echo "  \$CORPAUG to the factors used for lm"
   echo "  \$ORDER to lm order"
@@ -25,33 +19,37 @@ if [ -z "$CORP" ] \
   exit 1
 fi
 
-if [[ ! -d "$SRILMDIR1" ]] || [[ ! -d "$SRILMDIR2" ]]; then
-  echo "   SRILMDIR1: $SRILMDIR1"
-  echo "or SRILMDIR2: $SRILMDIR2"
-  echo "not found."
+SCRIPTS_ROOTDIR="`cat ../$BINARIES/scripts.rootdir`"
+BINDIR="`pwd`../$BINARIES/bin/"
+
+if [ ! -f ../$BINARIES/srilm.path ]; then
+  echo "SRILM not found in $BINARIES"
   exit 1
 fi
 
-if [[ x$BINARIZE == xyes ]] && [[ ! -d "$IRSTLMDIR" ]] ; then
-  echo "   IRSTLMDIR: $IRSTLMDIR"
-  echo "not found."
-  exit 1
+SRILMDIR1="`cat ../$BINARIES/srilm.path`/bin/"
+SRILMDIR2="`cat ../$BINARIES/srilm.path`/bin/i686/"
+
+if [ x$BINARIZE == xyes ]; then
+  if [ ! -f ../$BINARIES/irstlm.path ]; then
+    echo "Asking for LM binarization and IRSTLM not found in $BINARIES";
+    exit 1
+  fi
+  IRSTLMDIR="`cat ../$BINARIES/irstlm.path`/bin/"
+  lmtypetag=.blm
+else
+  lmtypetag=
 fi
 
 if [ -z "$PARTS" ]; then
   PARTS=1
 fi
 
-if [ x$BINARIZE == xyes ]; then
-  lmtypetag=.blm
-else
-  lmtypetag=
-fi
-
 # Remember the core settings
 echo $CORP+$CORPAUG.$ORDER$lmtypetag > eman.tag
 
 cat << KONEC > eman.vars
+BINARIES=$BINARIES
 CORP=$CORP
 CORPAUG=$CORPAUG
 ORDER=$ORDER
@@ -160,7 +158,3 @@ echo "== Hostname:  "\`hostname\`
 echo "== Directory: "\`pwd\`
 echo "=============================="
 KONEC
-
-if [ "$RUN" == "yes" ]; then
-  sh eman.command
-fi
