ported the whole pipeline, seems to work now
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@1465 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/mert b/playground/eman.seeds/mert
--- a/playground/eman.seeds/mert
+++ b/playground/eman.seeds/mert
@@ -4,23 +4,12 @@
 function die() { echo "$@" | tee FAILED >&2; exit 1 ; }
 set -o pipefail
 
-if [ -z "$BINARIES" ]; then
-  echo "Set \$BINARIES to the step containing compiled tools"
-  exit 1
-fi
-
-SCRIPTS_ROOTDIR="`cat ../$BINARIES/scripts.rootdir`"
-MOSESCMD="`pwd`/../$BINARIES/bin/moses"
-
-SCORENBEST=/home/bojar/diplomka/granty/euromatrix/treedecode/trunk/scorenbest.asm
-TESTBLEU=/home/bojar/diplomka/granty/euromatrix/treedecode/trunk/testbleu.asm
-
-if [ -z "$MODELEXP" ] || [ -z "$DEVCORP" ] \
+if [ -z "$MODELSTEP" ] || [ -z "$DEVCORP" ] \
   || [ -z "$TESTCORP" ] \
   || [ -z "$REFAUG" ] \
   ; then
   echo "You must set: "
-  echo "  \$MODELEXP to the directory that contains the model, incl. all files"
+  echo "  \$MODELSTEP to the directory that contains the model, incl. all files"
   echo "  \$DEVCORP to the corpus for tuning"
   echo "  \$TESTCORP to the corpus for evaluation"
   echo "  \$REFAUG to the target (reference) lang+factors"
@@ -38,8 +27,32 @@ if [ -z "$MODELEXP" ] || [ -z "$DEVCORP" ] \
   echo "  \$ZMERTSEMPOSBLEUWEIGHTS for --semposbleu-weights, e.g. 1:1"
   echo "  \$ZMERTFLAGS for zmert flags"
   echo "  \$TMT_ROOT for zmert SemPOS TMT_ROOT"
+  echo "  \$BINARIES if you don't want to inherit them from MODELSTEP"
   exit 1
 fi
+
+echo $MODELSTEP > eman.deps
+
+# Load variables from MODEL
+[ -e ../$MODELSTEP/eman.vars ] || die "Bad translation model: $MODELSTEP"
+SAVEBINARIES=$BINARIES
+# inherit all variables
+eval `cat ../$MODELSTEP/eman.vars` || exit 1
+
+if [ -z "$SAVEBINARIES" ] || [ "$BINARIES" == "$SAVEBINARIES" ]; then
+  # inheriting, ignoring our SAVEBINARIES
+  true
+else
+  # using our own
+  BINARIES=$SAVEBINARIES
+  echo $BINARIES >> eman.deps
+fi
+
+SCRIPTS_ROOTDIR="`pwd`/../$BINARIES/moses/scripts"
+MOSESCMD="`pwd`/../$BINARIES/bin/moses"
+
+SCORENBEST=/home/bojar/diplomka/granty/euromatrix/treedecode/trunk/scorenbest.asm
+TESTBLEU=/home/bojar/diplomka/granty/euromatrix/treedecode/trunk/testbleu.asm
 
 [ ! -z "$SEARCH" ] || SEARCH=beam
 [ ! -z "$MERTPRG" ] || MERTPRG=mert
@@ -62,21 +75,17 @@ if [ "$MERTPRG" == zmert ]; then
 fi
 
 
-echo $TAGPREF`cat ../$MODELEXP/eman.tag`"DEV"$DEVCORP".S"$SEARCH$STACK$MERTTAG > eman.tag
+echo $TAGPREF`cat ../$MODELSTEP/eman.tag`"DEV"$DEVCORP".S"$SEARCH$STACK$MERTTAG > eman.tag
 
-echo SETTING eman.tag: `cat eman.tag`
+#echo SETTING eman.tag: `cat eman.tag`
 
-SAVEMODELEXP=$MODELEXP
-eval `cat ../$MODELEXP/eman.vars` || exit 1
-MODELEXP=$SAVEMODELEXP
-
-echo $MODELEXP > eman.deps
 echo $BINARIES >> eman.deps
 
-echo $MODELEXP > info.modelexp
+echo $MODELSTEP > info.modelexp
 
 cat << KONEC > eman.vars
-MODELEXP=$MODELEXP
+BINARIES=$BINARIES
+MODELSTEP=$MODELSTEP
 DEVCORP=$DEVCORP
 TESTCORP=$TESTCORP
 SRCAUG=$SRCAUG
@@ -176,9 +185,9 @@ $ZMERTMOSES \
 KONEC
 ;;
 mert)
+  #--obo-scorenbest=\`pwd\`/scorenbest
   cat << KONEC > command.mert
 $MERTMOSES \
-  --obo-scorenbest=\`pwd\`/scorenbest \\
   --working-dir=mert-tuning \\
   \`pwd\`/tuning.in \\
   \`pwd\`/tuning.ref. \\
@@ -206,8 +215,10 @@ echo "=============================="
 # init grid environment
 . /net/projects/SGE/user/sge_profile
 
+mydir=\`pwd\`
+
 set -o pipefail
-function die() { echo "\$@" | tee FAILED >&2; exit 1 ; }
+function die() { echo "\$@" >&2 ; echo FAILED > \$mydir/eman.status ; exit 1 ; }
 
 renice 10 \$\$
 
@@ -230,8 +241,8 @@ echo export MERTFLAGS="$MERTFLAGS"
 
 ## Clone the moses.ini and source files
 \$SCRIPTS_ROOTDIR/training/clone_moses_model.pl \
-  ../$MODELEXP/model/moses.ini \
-  || die "Failed to clone ../$MODELEXP/model/moses.ini"
+  ../$MODELSTEP/model/moses.ini \
+  || die "Failed to clone ../$MODELSTEP/model/moses.ini"
 
 ## We're using irstlm, change the lmodel-file type:
 # ../set_lm_type.pl ./moses.ini || die "Failed to set lmtype" || exit 1
diff --git a/playground/eman.seeds/model b/playground/eman.seeds/model
--- a/playground/eman.seeds/model
+++ b/playground/eman.seeds/model
@@ -7,50 +7,59 @@
 set -o pipefail
 function die() { echo "$@" | tee FAILED >&2; exit 1 ; }
 
-if [ -z "$BINARIES" ]; then
-  echo "Set \$BINARIES to the step containing compiled tools"
-  exit 1
-fi
-
-SCRIPTS_ROOTDIR="`cat ../$BINARIES/scripts.rootdir`"
-
-if [ -z "$TMEXP" ] || [ -z "$LMEXPS" ] \
+if [ -z "$TMSTEP" ] || [ -z "$LMS" ] \
   ; then
   echo "You must set: "
-  echo "  \$TMEXP to the extracted phrases"
-  echo "  \$LMEXPS to factor:lmdir:::factor:lmdir:::factor:lmdir"
+  echo "  \$TMSTEP to the extracted phrases"
+  echo "  \$LMS to factor:lmstep:::factor:lmstep:::factor:lmstep"
   echo "And optionally:"
-  echo "  \$RMEXP to reordering models"
+  echo "  \$RMSTEP to reordering models"
+  echo "  \$BINARIES if you don't want to inherit them from TMSTEP"
   exit 1
 fi
 
-# Load variables from TMexp
-[ -e ../$TMEXP/eman.vars ] || die "Bad translation model: $TMEXP"
-. ../$TMEXP/eman.vars
+# Load variables from TMSTEP
+[ -e ../$TMSTEP/eman.vars ] || die "Bad translation model: $TMSTEP"
+SAVEBINARIES=$BINARIES
+# inherit all variables
+source ../$TMSTEP/eman.vars
+
+if [ -z "$SAVEBINARIES" ] || [ "$BINARIES" == "$SAVEBINARIES" ]; then
+  # inheriting, ignoring our SAVEBINARIES
+  true
+else
+  # using our own
+  BINARIES=$SAVEBINARIES
+  echo $BINARIES >> eman.deps
+fi
+
+SCRIPTS_ROOTDIR="`pwd`/../$BINARIES/moses/scripts"
+WORKSPACE="`pwd`/../$BINARIES/"
 
 # Load variables from RMexp
-if [ -z "$RMEXP" ]; then
+if [ -z "$RMSTEP" ]; then
   REORDERING=distance
   REORDFACTORS="0-0"
   DOTREORDTAG=""
 else
-  [ "$SRCAUG" == $(cat ../$RMEXP/var-SRCAUG) ] || die "Incompatible SRCAUGs"
-  [ "$TGTAUG" == $(cat ../$RMEXP/var-TGTAUG) ] || die "Incompatible TGTAUGs"
-  REORDERING=`cat ../$RMEXP/var-REORDERING` || die "Missed REORDERING"
-  REORDFACTORS=`cat ../$RMEXP/var-REORDFACTORS` || die "Missed REORDFACTORS"
-  REORDTAG=`cat ../$RMEXP/var-REORDTAG` || die "Missed REORDTAG"
+  [ "$SRCAUG" == $(cat ../$RMSTEP/var-SRCAUG) ] || die "Incompatible SRCAUGs"
+  [ "$TGTAUG" == $(cat ../$RMSTEP/var-TGTAUG) ] || die "Incompatible TGTAUGs"
+  REORDERING=`cat ../$RMSTEP/var-REORDERING` || die "Missed REORDERING"
+  REORDFACTORS=`cat ../$RMSTEP/var-REORDFACTORS` || die "Missed REORDFACTORS"
+  REORDTAG=`cat ../$RMSTEP/var-REORDTAG` || die "Missed REORDTAG"
   [ ! -z "$REORDERING" ] && [ ! -z "$REORDFACTORS" ] && [ ! -z "$REORDTAG" ] \
-    || die "Bad reordering model: $RMEXP"
+    || die "Bad reordering model: $RMSTEP"
   DOTREORDTAG=".$REORDTAG"
 fi
 
-echo "Print and save used variables:"
-cat << KONEC | tee eman.vars
-TMEXP=$TMEXP
-RMEXP=$RMEXP
-LMEXPS=$LMEXPS
+cat > eman.vars << KONEC
+BINARIES=$BINARIES
+TMSTEP=$TMSTEP
+RMSTEP=$RMSTEP
+LMS=$LMS
 SRCCORP=$SRCCORP
 TGTCORP=$TGTCORP
+ALISTEP=$ALISTEP
 ALICORP=$ALICORP
 SRCAUG=$SRCAUG
 TGTAUG=$TGTAUG
@@ -63,26 +72,25 @@ KONEC
 echo $SRCAUG > var-SRCAUG
 echo $TGTAUG > var-TGTAUG
 
-echo $TMEXP > eman.deps
-echo $BINARIES >> eman.deps
+echo $TMSTEP >> eman.deps
 
-[ -z "$RMEXP" ] || echo $RMEXP >> eman.deps
+[ -z "$RMSTEP" ] || echo $RMSTEP >> eman.deps
 
 ## Create the tag based on LMs
 i=1
-for lm in `echo $LMEXPS | sed 's/:::/ /g'`; do
-  eval `makearg --delim=: $lm factor lmdir lmtype`
-  echo $lmdir >> eman.deps
+for lm in `echo $LMS | sed 's/:::/ /g'`; do
+  eval `makearg --delim=: $lm factor lmstep lmtype`
+  echo $lmstep >> eman.deps
   # default to sri
   lmtypetag=${lmtype:-sri}
-  order=`cat ../$lmdir/var-ORDER` || die "Missing: ../$lmdir/var-ORDER"
+  order=`cat ../$lmstep/var-ORDER` || die "Missing: ../$lmstep/var-ORDER"
   i=$(($i+1))
   factor=`echo $factor | sed 'y/\,/+/'`
-  lmtag=$lmtag"LM$factor-$order-"`cat ../$lmdir/eman.tag`-$lmtypetag
+  lmtag=$lmtag"LM$factor-$order-"`cat ../$lmstep/eman.tag`-$lmtypetag
 done
 i=$(($i-1))
 
-eval "cat ../$TMEXP/eman.vars | grep 'THRESHOLD\|CUTOFF'"
+eval "cat ../$TMSTEP/eman.vars | grep 'THRESHOLD\|CUTOFF'"
 if [ ! -z "$THRESHOLD" ]; then
   SIGFILTERTAG=SIG$THRESHOLD"N"$CUTOFF
 fi
@@ -116,7 +124,7 @@ echo "=============================="
 mydir=\`pwd\`
 
 set -o pipefail
-function die() { echo "\$@" | tee \$mydir/FAILED >&2; exit 1 ; }
+function die() { echo "\$@" >&2 ; echo FAILED > \$mydir/eman.status ; exit 1 ; }
 
 renice 10 \$\$
 
@@ -125,16 +133,16 @@ echo SCRIPTS_ROOTDIR=$SCRIPTS_ROOTDIR
 
 ## Cloning translation model
 cd model || die "Chdir failed"
-for f in ../../$TMEXP/model/*gz ; do
+for f in ../../$TMSTEP/model/*gz ; do
   wiseln \$f ./\`basename \$f\` || die "Failed to clone \$f"
 done
 cd \$mydir || die "Chdir back failed"
 
 
 ## Cloning reordering model
-if [ ! -z "$RMEXP" ]; then
+if [ ! -z "$RMSTEP" ]; then
   cd model || die "Chdir failed"
-  for f in ../../$RMEXP/model/reordering-table*gz ; do
+  for f in ../../$RMSTEP/model/reordering-table*gz ; do
     wiseln \$f ./\`basename \$f\` || die "Failed to clone \$f"
   done
   cd \$mydir || die "Chdir back failed"
@@ -144,9 +152,9 @@ fi
 ## Clone the lms
 echo "Cloning LMs"
 i=1
-for lm in \`echo $LMEXPS | sed 's/:::/ /g'\`; do
-  eval \`makearg --delim=: \$lm factor lmdir lmtype\`
-  echo "Cloning lm from \$lmdir, using lmtype \$lmtype"
+for lm in \`echo $LMS | sed 's/:::/ /g'\`; do
+  eval \`makearg --delim=: \$lm factor lmstep lmtype\`
+  echo "Cloning lm from \$lmstep, using lmtype \$lmtype"
   if [ x\$lmtype == xblm ]; then
     numericlmtype=1
     lmsuffix=blm
@@ -159,14 +167,14 @@ for lm in \`echo $LMEXPS | sed 's/:::/ /g'\`; do
   fi
 
   if [ \$lmsuffix == flm ]; then
-    wiseln ../\$lmdir/config.prepared.flm ./lm.\$i.\$lmsuffix \\
-      || die "Failed to link flm: ../\$lmdir/config.prepared.flm"
+    wiseln ../\$lmstep/config.prepared.flm ./lm.\$i.\$lmsuffix \\
+      || die "Failed to link flm: ../\$lmstep/config.prepared.flm"
   else
-    wiseln ../\$lmdir/corpus.\$lmsuffix ./lm.\$i.\$lmsuffix \\
-      || die "Failed to link lm: ../\$lmdir/corpus.\$lmsuffix"
+    wiseln ../\$lmstep/corpus.\$lmsuffix ./lm.\$i.\$lmsuffix \\
+      || die "Failed to link lm: ../\$lmstep/corpus.\$lmsuffix"
   fi
 
-  order=\`cat ../\$lmdir/var-ORDER\` || die "Missing: ../\$lmdir/var-ORDER"
+  order=\`cat ../\$lmstep/var-ORDER\` || die "Missing: ../\$lmstep/var-ORDER"
 
   lmopts="\$lmopts --lm \$factor:\$order:\$mydir/lm.\$i.\$lmsuffix:\$numericlmtype"
   i=\$((\$i+1))
@@ -175,7 +183,7 @@ i=\$((\$i-1))
 
 echo lmopts: \$lmopts
 
-\$SCRIPTS_ROOTDIR/training/train-factored-phrase-model.perl \\
+\$SCRIPTS_ROOTDIR/training/train-model.perl \\
     --force-factored-filenames \\
     --first-step 9 --last-step 9 \\
     --root-dir . \\
@@ -198,8 +206,4 @@ echo "== Hostname:  "\`hostname\`
 echo "== Directory: "\`pwd\`
 echo "=============================="
 KONEC
-
-if [ "$RUN" == "yes" ]; then
-  sh eman.command
-fi
 
