adding a sample experiment and an example how to use it in README other minor fixes
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@1596 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/model b/playground/eman.seeds/model
--- a/playground/eman.seeds/model
+++ b/playground/eman.seeds/model
@@ -214,7 +214,8 @@ for tm in \`echo $TMS | tr ':' ' '\`; do
 done
 
 mkdir model
-../../scripts/merge_moses_models.pl tm.*/model/moses.ini > ./model/moses.ini
+../../scripts/merge_moses_models.pl tm.*/model/moses.ini > ./model/moses.ini \
+  || die "Merge moses.ini failed"
 
 echo DONE > \$mydir/eman.status
 
