many small fixes in model seed
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@2710 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/model b/playground/eman.seeds/model
--- a/playground/eman.seeds/model
+++ b/playground/eman.seeds/model
@@ -21,10 +21,20 @@ eman \
 # Set local bash variables
 eval `eman bash-loadvars`
 
+# Eman should support inheriting many vars from a step at once
 tmone=`echo $TMS | cut -d: -f1`
 eman \
-  defvar MOSESSTEP type='reqstep' inherit="$tmone" help="Failed to inherit from $tmone" \
+  defvar MOSESSTEP type='reqstep' default="$(eman get-var $tmone BINARIES)" \
+    help="Failed to inherit from $tmone" \
+  defvar SRCAUG default="$(eman get-var $tmone SRCAUG)" \
+  defvar TGTAUG default="$(eman get-var $tmone TGTAUG)" \
+  defvar DECODINGSTEPS default="$(eman get-var $tmone DECODINGSTEPS)" \
+  defvar THRESHOLD default="$(eman get-var $tmone THRESHOLD)" \
+  defvar CUTOFF default="$(eman get-var $tmone CUTOFF)" \
 || exit 1
+
+# Set (update) local bash variables
+eval `eman bash-loadvars`
 
 eman add-deps . $MOSESSTEP
 
@@ -43,8 +53,7 @@ else
   [ "$TGTAUG" == $(eman get-var $RMSTEP TGTAUG) ] || die "Incompatible TGTAUGs"
   REORDERING=$(eman get-var $RMSTEP REORDERING) || die "Missed REORDERING"
   REORDFACTORS=$(eman get-var $RMSTEP REORDFACTORS) || die "Missed REORDFACTORS"
-  REORDTAG=$(eman get-var $RMSTEP REORDTAG) || die "Missed REORDTAG"
-  [ ! -z "$REORDERING" ] && [ ! -z "$REORDFACTORS" ] && [ ! -z "$REORDTAG" ] \
+  [ ! -z "$REORDERING" ] && [ ! -z "$REORDFACTORS" ] \
     || die "Bad reordering model: $RMSTEP"
   DOTREORDTAG=".$REORDTAG"
 fi
@@ -61,7 +70,8 @@ done
 i=1
 for lm in `echo $LMS | sed 's/:::/ /g'`; do
   eval `$PLAYGROUND/../scripts/makearg --delim=: $lm factor lmstep lmtype`
-  echo $lmstep >> eman.deps
+  [ ! -z "$lmstep" ] || die "Bad LM specifier: $lm, expected <factor>:<lmstep>"
+  eman add-deps . $lmstep
   # default to kenlm
   lmtypetag=${lmtype:-ken}
   order=`eman get-var $lmstep ORDER` || die "Missing variable $lmstep:ORDER"
@@ -71,17 +81,16 @@ for lm in `echo $LMS | sed 's/:::/ /g'`; do
 done
 i=$(($i-1))
 
-THRESHOLD=`eman var $tmone THRESHOLD`
-CUTOFF=`eman var $tmone CUTOFF`
 if [ ! -z "$THRESHOLD" ]; then
   SIGFILTERTAG=SIG$THRESHOLD"N"$CUTOFF
 fi
 
-if [ $SRCCORP == $TGTCORP ] ; then
-  eman add-tag "SRC$SRCCORP+$SRCAUG.TGT+$TGTAUG.ALI$ALIAUG.$tmtag.$lmtag.$DECODINGSTEPS$DOTREORDTAG$SIGFILTERTAG"
-else
-  eman add-tag "SRC$SRCCORP+$SRCAUG.TGT$TGTCORP+$TGTAUG.ALI$ALIAUG.$tmtag.$lmtag.$DECODINGSTEPS$DOTREORDTAG$SIGFILTERTAG"
-fi
+echo "Unimplemented for the moment: creation of tags"
+#if [ $SRCCORP == $TGTCORP ] ; then
+#  eman add-tag "SRC$SRCCORP+$SRCAUG.TGT+$TGTAUG.ALI$ALIAUG.$tmtag.$lmtag.$DECODINGSTEPS$DOTREORDTAG$SIGFILTERTAG"
+#else
+#  eman add-tag "SRC$SRCCORP+$SRCAUG.TGT$TGTCORP+$TGTAUG.ALI$ALIAUG.$tmtag.$lmtag.$DECODINGSTEPS$DOTREORDTAG$SIGFILTERTAG"
+#fi
 
 # Stop here if we are just initing ourselves
 [ -z "$INIT_ONLY" ] || exit 0
@@ -98,13 +107,11 @@ echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
 echo "== Hostname:  "\`hostname\`
 echo "== Directory: "\`pwd\`
 echo "=============================="
-
-mydir=\`pwd\`
-
+mydir=\$(pwd)
 set -o pipefail
-function die() { echo "\$@" >&2 ; echo FAILED > \$mydir/eman.status ; exit 1 ; }
-
+function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }
 renice 10 \$\$
+ulimit -c 1 # core files limited to 1 byte
 
 export SCRIPTS_ROOTDIR=$SCRIPTS_ROOTDIR
 echo SCRIPTS_ROOTDIR=$SCRIPTS_ROOTDIR
@@ -205,8 +212,9 @@ mkdir model
 $PLAYGROUND/../scripts/merge_moses_models.pl --no-concat-lms tm.*/model/moses.ini > ./model/moses.ini \
   || die "Merge moses.ini failed"
 
-echo DONE > \$mydir/eman.status
-
+# Standard command footer
+echo Done.
+eman succeed \$mydir
 echo "=============================="
 echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
 echo "== Hostname:  "\`hostname\`
