reordering working again, new results
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@1803 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/model b/playground/eman.seeds/model
--- a/playground/eman.seeds/model
+++ b/playground/eman.seeds/model
@@ -152,9 +152,10 @@ done
 
 ## Cloning reordering model
 if [ ! -z "$RMSTEP" ]; then
-  cd model || die "Chdir failed"
-  for f in ../../$RMSTEP/model/reordering-table*gz ; do
-    ../../scripts/wiseln \$f ./\`basename \$f\` || die "Failed to clone \$f"
+  cd tm.1/model || die "Failed to implant reordmodel to tm.1"
+  for f in ../../../$RMSTEP/model/reordering-table*gz ; do
+    ../../../../scripts/wiseln \$f ./\`basename \$f\` \\
+      || die "Failed to clone \$f"
   done
   cd \$mydir || die "Chdir back failed"
 fi
