Putting my autotagging recipe under version control.
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@3149 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/morfcorpus b/playground/eman.seeds/morfcorpus
--- a/playground/eman.seeds/morfcorpus
+++ b/playground/eman.seeds/morfcorpus
@@ -37,7 +37,7 @@ $STATMT/playground/corpman register -- corpus.txt.gz -1 $CORP~morf $LANG $FACT -
 [ -z "$INIT_ONLY" ] || exit 0
 
 # Convert the dependencies to absolute paths.
-MORFESSOR=`eman path $MORFESSORSTEP`/bin
+MORFESSOR=`eman path $MORFESSORSTEP`/morfessor/bin
 
 cat > eman.command << KONEC
 #!/bin/bash
@@ -53,7 +53,11 @@ renice 10 \$\$
 
 # Get the input corpus.
 corpspec=$CORP/$LANG+$FACT
-corpmanout=\$($STATMT/playground/corpman --wait \$corpspec)
+###!!! If we already have the stc factor but don't have the form factor, corpman goes wild.
+###!!! Without the --wait option, it returns the stc factor. With the option, it insists on having the form factor available first.
+###!!! So I am removing the --wait option from the following line, although it would be useful otherwise.
+corpmanout=\$($STATMT/playground/corpman \$corpspec)
+[ -n "\$corpmanout" ] || die "Input corpus \$corpspec not found"
 echo "corpman for \$corpspec returned: \$corpmanout" # for the log
 step_file_col=(\$corpmanout)
 corpfile="$STATMT/playground/\${step_file_col[0]}/\${step_file_col[1]}"
@@ -67,7 +71,7 @@ fi
 # Segment tokens into morphemes.
 ###!!! DZ: I am currently using my old segmentation models, fixed. Later I will refer to morfmodel steps instead.
 gunzip -c input.txt.gz \
-| $MORFESSOR/morfseg.pl -m /net/work/people/zeman/morfessor/$LANG/segmented.txt \
+| $MORFESSOR/morfseg.pl -m /net/work/people/zeman/morfessor.zaloha/$LANG/segmented.txt \
 | gzip -c > corpus.txt.gz
 # Get the number of lines and re-register the corpus.
 echo "Checking output number of lines of corpus.txt.gz"
@@ -76,7 +80,8 @@ echo "Re-registering the corpus with \$nl lines."
 $STATMT/playground/corpman register -- corpus.txt.gz -1 $CORP~morf $LANG $FACT \$nl 1 \\
 || die "Cannot register corpus"
 # Remove corpman.index, force reindexing.
-rm -f \$mydir/../corpman.index || echo "Failed to force reindexing"
+###!!! To je sice hezký, ale když poběží 50 takových kroků najednou a budou si pod rukama mazat index, tak si zaručeně někdo z nich dá na hubu.
+#rm -f \$mydir/../corpman.index || echo "Failed to force reindexing"
 
 # Standard command footer
 echo Done.
