bugfix
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@3448 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/multimerteval b/playground/eman.seeds/multimerteval
--- a/playground/eman.seeds/multimerteval
+++ b/playground/eman.seeds/multimerteval
@@ -85,7 +85,7 @@ eman wait \$EVALSTEPS
 echo "Evaluator steps finished."
 
 for evalstep in \$EVALSTEPS ; do
-  [ \$(cat \$evalstep/eman.status) -eq DONE ] || die "Step failed: \$evalstep"
+  [ \$(cat \$evalstep/eman.status) = DONE ] || die "Step failed: \$evalstep"
   SCORE=\$(cat \$evalstep/scores | grep BLEU | cut -f2)
   TOTAL=\$(echo "\$TOTAL + \$SCORE" | bc -l)
 done
