applied bug fixes from tm in seed rm
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@2718 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/rm b/playground/eman.seeds/rm
--- a/playground/eman.seeds/rm
+++ b/playground/eman.seeds/rm
@@ -5,15 +5,15 @@ set -o pipefail
 function die() { echo "$@" | tee FAILED >&2; exit 1 ; }
 
 eman \
-  defvar ALISTEP type=reqstep default='' help="the step where alignment was constructed" \
+  defvar ALISTEP type='optstep' help="the step where alignment was constructed, implied by ALICORP+ALISYM+ALILABEL" \
   defvar BINARIES type=reqstep inherit=ALISTEP:GIZASTEP \
-    help="the step containing compiled tools; inherited from ALISTEP" \
+    help="the step containing compiled tools" \
   defvar SRCCORP inherit=ALISTEP:CORPUS \
-    help="source corpus name, CORPUS from ALISTEP is used if omitted" \
+    help="source corpus name" \
   defvar TGTCORP same_as=SRCCORP help="target corpus name, can be omitted if equal to SRCCORP" \
   defvar SRCAUG help="the string describing lang+factors of src corpus" \
   defvar TGTAUG help="the string describing lang+factors of tgt corpus" \
-  defvar ALICORP same_as=SRCCORP help="target corpus name, can be omitted if equal to SRCCORP" \
+  defvar ALICORP same_as=SRCCORP help="alignment corpus name, can be omitted if equal to SRCCORP" \
   defvar ALISYM default='gdfa' help='which alignment to use for the reordering model' \
   defvar ALILABEL inherit=ALISTEP \
     help="the custom label as given when creating the alignment" \
@@ -24,13 +24,21 @@ eman \
 
 eval `eman bash-loadvars`
 
-[ `eman getvar $ALISTEP CORPUS` == $SRCCORP ] \
-  || die "Nonmatching alistep: different corpus"
-[ `eman getvar $ALISTEP ALILABEL` == $ALILABEL ] \
-  || die "Nonmatching alistep: different ALILABEL"
-
-[ -z $ALISTEP ] || ALISTEP=`eman path $ALISTEP`
 PLAYGROUND=`eman path`
+
+if [ -z "$ALISTEP" ]; then
+  echo "Finding alistep that provides $ALICORP/$ALISYM-$ALILABEL"
+  export ALISTEP=`$PLAYGROUND/corpman $ALICORP/$ALISYM-$ALILABEL+ali | cut -f1`
+  echo "Found ALISTEP=$ALISTEP"
+  eman add-dep . "$ALISTEP" || die "Failed to depend on alistep $ALISTEP"
+  eman defvar ALISTEP
+fi
+
+[ "$(eman getvar $ALISTEP CORPUS)" == "$SRCCORP" ] \
+  || die "Nonmatching alistep: different corpus"
+[ "$(eman getvar $ALISTEP ALILABEL)" == "$ALILABEL" ] \
+  || die "Nonmatching alistep: different ALILABEL: our is $ALILABEL"
+
 BINARIESDIR=`eman path $BINARIES`
 SCRIPTS_ROOTDIR="$BINARIESDIR/moses/scripts"
 
