seed subcorp now works with corpora lacking lang.factors dir
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@1497 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/subcorp b/playground/eman.seeds/subcorp
--- a/playground/eman.seeds/subcorp
+++ b/playground/eman.seeds/subcorp
@@ -65,15 +65,17 @@ for f in *.info; do
     zcat ../$OUTCORPNAME/\$lang.gz | wc -l > ../$OUTCORPNAME/LINECOUNT \\
     || die "Failed to construct LINECOUNT"
   
-    for fact in \$lang.factors/*.gz; do
-      factor=\$(basename \${fact//.gz})
-      echo "Making subcorpus for factor \$factor of lang \$lang"
-      mkdir -p ../$OUTCORPNAME/\$lang.factors
-  
-      ../augment.pl $CORPUS/\$lang+\$factor --dump --subcorpus="$SUBSET" \\
-      | gzip -c > ../$OUTCORPNAME/\$lang.factors/\$factor.gz \\
-      || die "Failed to create factor \$factor"
-    done
+    if [ -d \$lang.factors ] && [ \`ls \$lang.factors | wc -l\` ]; then
+      for fact in \$lang.factors/*.gz; do
+        factor=\$(basename \${fact//.gz})
+        echo "Making subcorpus for factor \$factor of lang \$lang"
+        mkdir -p ../$OUTCORPNAME/\$lang.factors
+    
+        ../augment.pl $CORPUS/\$lang+\$factor --dump --subcorpus="$SUBSET" \\
+        | gzip -c > ../$OUTCORPNAME/\$lang.factors/\$factor.gz \\
+        || die "Failed to create factor \$factor"
+      done
+    fi
   fi
 done
 
