support specifying either ALISTEP or ALICORP+ALILABEL+ALISYM
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@2715 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/tm b/playground/eman.seeds/tm
--- a/playground/eman.seeds/tm
+++ b/playground/eman.seeds/tm
@@ -5,7 +5,7 @@ set -o pipefail
 function die() { echo "$@" | tee FAILED >&2; exit 1 ; }
 
 eman \
-  defvar ALISTEP type=reqstep help="the step where alignment was constructed" \
+  defvar ALISTEP help="the step where alignment was constructed, implied by ALICORP+ALISYM+ALILABEL" \
   defvar BINARIES type=reqstep inherit=ALISTEP:GIZASTEP \
     help="the step containing compiled tools" \
   defvar SRCCORP inherit=ALISTEP:CORPUS \
@@ -25,13 +25,21 @@ eman \
 
 eval `eman bash-loadvars`
 
+PLAYGROUND=`eman path`
+
+if [ -z "$ALISTEP" ]; then
+  echo "Finding alistep that provides $ALICORP/$ALISYM-$ALILABEL"
+  export ALISTEP=`$PLAYGROUND/corpman $ALICORP/$ALISYM-$ALILABEL+ali | cut -f1`
+  echo "Found ALISTEP=$ALISTEP"
+  eman add-dep . "$ALISTEP" || die "Failed to depend on alistep $ALISTEP"
+  eman defvar ALISTEP
+fi
+
 [ `eman getvar $ALISTEP CORPUS` == $SRCCORP ] \
   || die "Nonmatching alistep: different corpus"
-[ `eman getvar $ALISTEP ALILABEL` == $ALILABEL ] \
-  || die "Nonmatching alistep: different ALILABEL"
+[ "$(eman getvar $ALISTEP ALILABEL)" == "$ALILABEL" ] \
+  || die "Nonmatching alistep: different ALILABEL: our is $ALILABEL"
 
-[ -z $ALISTEP ] || ALISTEP=`eman path $ALISTEP`
-PLAYGROUND=`eman path`
 BINARIES=`eman path $BINARIES`
 SCRIPTS_ROOTDIR="$BINARIES/moses/scripts"
 
