Full path to zwc in tm seed.
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@2798 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/tm b/playground/eman.seeds/tm
--- a/playground/eman.seeds/tm
+++ b/playground/eman.seeds/tm
@@ -178,8 +178,8 @@ fi
 [ \$success == 1 ] || die "THERE WERE ERRORS!! See above."
 
 echo "Getting phrase counts..."
-zwc -l model/*.gz | tee phrase-counts
- 
+( $PLAYGROUND/tools/zwc -l model/*.gz | tee phrase-counts ) || die "Failed to count phrases"
+
 
 # Standard command footer
 echo Done.
