updated seed tm, rm
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@2676 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/tm b/playground/eman.seeds/tm
--- a/playground/eman.seeds/tm
+++ b/playground/eman.seeds/tm
@@ -4,62 +4,32 @@
 set -o pipefail
 function die() { echo "$@" | tee FAILED >&2; exit 1 ; }
 
-if [ -z "$DECODINGSTEPS" ] \
-  || ( [ -z "$SRCCORP" ] && [ -z "$ALISTEP" ] ) \
-  || [ -z "$SRCAUG" ] \
-  || [ -z "$TGTAUG" ] \
-  || ( [ -z "$ALIAUG" ] && [ -z "$ALISTEP" ] ) \
-  || ( [ -z "$BINARIES" ] && [ -z "$ALISTEP" ] ) \
-  ; then
-  echo "You must set: "
-  echo "  \$BINARIES to the step containing compiled tools; inherited from ALISTEP"
-  echo "  \$SRCCORP to source corpus name, CORPUS from ALISTEP is used if omitted"
-  echo "  \$TGTCORP to target corpus name, can be omitted if equal to SRCCORP"
-  echo "  \$SRCAUG to the string describing lang+factors of src corpus"
-  echo "  \$TGTAUG same for target, e.g. cs+0+1+pos+lc"
-  echo "  \$ALICORP to target corpus name, can be omitted if equal to SRCCORP"
-  echo "  \$ALIAUG to the string describing the 'language', e.g. 'ali'"
-  echo "    or \$ALISTEP to the step where alignment was constructed"
-  echo "  \$DECODINGSTEPS to specification of decoding steps, e.g. 0a1-0+1-1"
-  echo "And optionally:"
-  echo "  \$REORDERING to reordering models, eg. orientation-bidirectional-fe"
-  echo "  \$REORDFACTORS to factors to use, eg. 0,1-0+0-0"
-  echo "  \$TRAININGFLAGS to flags for train-factored-phrase-model.perl"
-  echo "And optionally for sigfiltering:"
-  echo "  \$THRESHOLD to a+e, a-e of a number (see moses/sigtest-filter)"
-  echo "  \$CUTOFF to phrase-table cutoff"
-  exit 1
-fi
+eman \
+  defvar ALISTEP type=reqstep default='' help="the step where alignment was constructed" \
+  defvar type=reqstep inherit=ALISTEP BINARIES \
+    help="the step containing compiled tools; inherited from ALISTEP" \
+  defvar SRCCORP help="source corpus name, CORPUS from ALISTEP is used if omitted" \
+  defvar TGTCORP sameas=SRCCORP help="target corpus name, can be omitted if equal to SRCCORP" \
+  defvar SRCAUG help="the string describing lang+factors of src corpus" \
+  defvar TGTAUG help="the string describing lang+factors of tgt corpus" \
+  defvar ALICORP sameas=SRCCORP help="target corpus name, can be omitted if equal to SRCCORP" \
+  defvar ALIAUG inherit=ALISTEP:OUTALILABEL \
+    help="the string describing the 'language', e.g. 'ali'" \
+  defvar DECODINGSTEPS help="specification of decoding steps, e.g. 0a1-0+1-1" \
+  defvar REORDERING default='distance' \
+    help="reordering models, eg. orientation-bidirectional-fe" \
+  defvar REORDFACTORS default='0-0' help="factors to use, eg. 0,1-0+0-0" \
+  defvar TRAININGFLAGS default='' help="flags for train-factored-phrase-model.perl" \
+  defvar THRESHOLD default='' help="a+e, a-e of a number (see moses/sigtest-filter)" \
+  defvar CUTOFF default=0 help="phrase-table cutoff" \
+|| exit 1
 
-# load inherited/inheritable binaries
-[ ! -z "$ALISTEP" ] \
-  && INHER_BINARIES=`cat ../$ALISTEP/eman.vars | grep ^BINARIES | cut -d= -f2`
+eval `eman bash-loadvars`
 
-if [ -z "$BINARIES" ] || [ "$INHER_BINARIES" == "$BINARIES" ]; then
-  # inherit binaries from alistep
-  BINARIES=$INHER_BINARIES
-  # inherited binaries don't belong to our dependencies, we
-  # hope our predecessor has them as a dependence
-else
-  # put BINARIES to our deps as well
-  echo $BINARIES >> eman.deps
-fi
-SCRIPTS_ROOTDIR="`pwd`/../$BINARIES/moses/scripts"
-WORKSPACE="`pwd`/../$BINARIES/"
-
-# get ali corpus and aug from alistep
-if [ ! -z "$ALISTEP" ]; then
-  ALICORP=`cat ../$ALISTEP/eman.vars | grep ^CORPUS | cut -d= -f2`
-  ALIAUG=`cat ../$ALISTEP/eman.vars | grep ^OUTALILABEL | cut -d= -f2`
-  [ ! -z "$SRCCORP" ] || SRCCORP=$ALICORP # only set SRCCORP if it wasn't specified
-  echo $ALISTEP >> eman.deps
-fi
-
-# TGT and ALI corp default to srccorp
-[ ! -z "$TGTCORP" ] || TGTCORP=$SRCCORP
-[ ! -z "$ALICORP" ] || ALICORP=$SRCCORP
-
-[ ! -z "$CUTOFF" ] || CUTOFF=0
+[ -z $ALISTEP ] || ALISTEP=`eman path $ALISTEP`
+PLAYGROUND=`eman path`
+BINARIES=`eman path $BINARIES`
+SCRIPTS_ROOTDIR="$BINARIES/moses/scripts"
 
 if echo "$DECODINGSTEPS" | grep , ; then
   echo "\$DECODINGSTEPS ($DECODINGSTEPS) contains a comma! Use 'a' instead, e.g. 0a1-0+1-1"
@@ -78,40 +48,19 @@ else
   DOTREORDTAG=`echo ".$REORDERING.r$REORDFACTORS" | sed 's/\([a-z][a-z]\)[a-z]*/\1/g'`
 fi
 
-cat << KONEC > eman.vars
-BINARIES=$BINARIES
-SRCCORP=$SRCCORP
-TGTCORP=$TGTCORP
-ALICORP=$ALICORP
-SRCAUG=$SRCAUG
-TGTAUG=$TGTAUG
-ALISTEP=$ALISTEP
-ALIAUG=$ALIAUG
-DECODINGSTEPS=$DECODINGSTEPS
-REORDERING=$REORDERING
-REORDFACTORS=$REORDFACTORS
-TRAININGFLAGS="$TRAININGFLAGS"
-CUTOFF=$CUTOFF
-THRESHOLD=$THRESHOLD
-KONEC
-
-echo $SRCAUG > var-SRCAUG
-echo $TGTAUG > var-TGTAUG
-
 if [ $SRCCORP == $TGTCORP ] ; then
-  echo SRC$SRCCORP+$SRCAUG.TGT+$TGTAUG.ALI$ALIAUG.DEC$DECODINGSTEPS$DOTREORDTAG > eman.tag
+  eman add-tag "SRC$SRCCORP+$SRCAUG.TGT+$TGTAUG.ALI$ALIAUG.DEC$DECODINGSTEPS$DOTREORDTAG"
 else
-  echo SRC$SRCCORP+$SRCAUG.TGT$TGTCORP+$TGTAUG.ALI$ALIAUG.DEC$DECODINGSTEPS$DOTREORDTAG > eman.tag
+  eman add-tag "SRC$SRCCORP+$SRCAUG.TGT$TGTCORP+$TGTAUG.ALI$ALIAUG.DEC$DECODINGSTEPS$DOTREORDTAG"
 fi
 
 # Stop here if we are just initing ourselves
 [ -z "$INIT_ONLY" ] || exit 0
 
-DECRYPT=$WORKSPACE/../tools/decrypt_mapping_steps_for_training.pl
+DECRYPT=$PLAYGROUND/tools/decrypt_mapping_steps_for_training.pl
 [ -x $DECRYPT ] || die "Missing: $DECRYPT"
 
 DECRYPTEDSTEPS=`eval $DECRYPT $DECODINGSTEPS`
-
 
 cat << KONEC > eman.command
 # This is the command to be run here
@@ -128,6 +77,20 @@ function die() { echo "\$@" >&2 ; echo FAILED > \$mydir/eman.status ; exit 1 ; }
 
 renice 10 \$\$
 
+function mkcorpus() {
+  $PLAYGROUND/corpman --wait \$1 || die "Failed to prepare \$1"
+  step_file_col=(\$($PLAYGROUND/corpman \$1))
+  if [ "\${step_file_col[2]}" == "-1" ]; then
+    $PLAYGROUND/../scripts/wiseln $PLAYGROUND/\${step_file_col[0]}/\${step_file_col[1]} \\
+      corpus.\$2.gz \
+    || die "Failed to clone \$2 corpus \$1"
+  else
+    echo "Selecting the column from \$step_file_col"
+    eval \$($PLAYGROUND/corpman --cmd $1) \\
+    | gzip -c > corpus.\$2.gz
+  fi
+}
+
 ## Prepare the corpus from more factors
 export SCRIPTS_ROOTDIR=$SCRIPTS_ROOTDIR
 echo SCRIPTS_ROOTDIR=$SCRIPTS_ROOTDIR
@@ -135,18 +98,15 @@ echo SCRIPTS_ROOTDIR=$SCRIPTS_ROOTDIR
 mkdir corpus
 
 cd corpus
-../../../scripts/wiseln \`../../augmented_corpora/augment.pl $SRCCORP/$SRCAUG\` corpus.src.gz \\
-  || die "Failed to clone source corpus"
-../../../scripts/wiseln \`../../augmented_corpora/augment.pl $TGTCORP/$TGTAUG\` corpus.tgt.gz \\
-  || die "Failed to clone target corpus"
+mkcorpus $SRCCORP/$SRCAUG corpus.src
+mkcorpus $SRCCORP/$SRCAUG corpus.tgt
 cd ..
 
 if [ ! -z "$ALISTEP" ]; then
-  ../../scripts/wiseln ../$ALISTEP/alignment.gz alignment.custom.gz \
+  $PLAYGROUND/../scripts/wiseln $ALISTEP/alignment.gz alignment.custom.gz \
     || die "Failed to clone alignment file"
 else
-  ../../scripts/wiseln \`../augmented_corpora/augment.pl --ignore-blank-lines $ALICORP/$ALIAUG\` alignment.custom.gz \
-    || die "Failed to clone alignment file"
+  mkcorpus $ALICORP/$ALIAUG alignment.custom
 fi
 
 alilen=\`zcat alignment.custom.gz | wc -l\`
@@ -188,11 +148,11 @@ if \\
         $TRAININGFLAGS \\
 	    $DECRYPTEDSTEPS \\
   && echo "Now will filter translation models" \\
-  && $WORKSPACE/../tools/filter-several-phrasetables.pl \\
+  && $PLAYGROUND/tools/filter-several-phrasetables.pl \\
         --srccorp=$SRCCORP --srcaug=$SRCAUG \\
         --tgtcorp=$TGTCORP --tgtaug=$TGTAUG \\
         --cutoff=$CUTOFF --threshold=$THRESHOLD \\
-        --workspace=$WORKSPACE \\
+        --workspace=$BINARIES \\
         \$tempdir/model/phrase-table.* \\
   && echo "Now will extract generation models" \\
   && \$SCRIPTS_ROOTDIR/training/train-model.perl \\
