seeds tm and rm now look for alignment.gz when given ALISTEP
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@1508 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/tm b/playground/eman.seeds/tm
--- a/playground/eman.seeds/tm
+++ b/playground/eman.seeds/tm
@@ -141,8 +141,13 @@ wiseln \`../../augmented_corpora/augment.pl $TGTCORP/$TGTAUG\` corpus.tgt.gz \\
   || die "Failed to clone target corpus"
 cd ..
 
-wiseln \`../augmented_corpora/augment.pl --ignore-blank-lines $ALICORP/$ALIAUG\` alignment.custom.gz \
-  || die "Failed to clone alignment file"
+if [ ! -z "$ALISTEP" ]; then
+  wiseln $ALISTEP/alignment.gz alignment.custom.gz \
+    || die "Failed to clone alignment file"
+else
+  wiseln \`../augmented_corpora/augment.pl --ignore-blank-lines $ALICORP/$ALIAUG\` alignment.custom.gz \
+    || die "Failed to clone alignment file"
+fi
 
 alilen=\`zcat alignment.custom.gz | wc -l\`
 srclen=\`zcat corpus/corpus.src.gz | wc -l\`
