In seed toa, moved code that depends on DONE binaries to correct section.
Added inverting of alignment points output by Moses.


git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@1628 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/eman.seeds/toa b/playground/eman.seeds/toa
--- a/playground/eman.seeds/toa
+++ b/playground/eman.seeds/toa
@@ -78,9 +78,6 @@ echo $BINARIES >> eman.deps
 # Stop here if we are just initing ourselves
 [ -z "$INIT_ONLY" ] || exit 0
 
-# clone some importnant executables
-../../scripts/wiseln $MOSESCMD ./moses || exit 1
-
 ## We're using irstlm, change the lmodel-file type:
 # ../set_lm_type.pl ./moses.ini || die "Failed to set lmtype" || exit 1
 
@@ -88,13 +85,6 @@ echo $BINARIES >> eman.deps
 
 echo Checking eval corp size
 [ `wc -l < evaluation.in` -gt 0 ] || exit 1
-
-TARGETLAN_FOR_DETOKENIZER=`echo $REFAUG | sed 's/^\(..\).*/\1/'`
-if ! echo "test" | $SCRIPTS_ROOTDIR/recaser/detokenizer.perl \
-       -u -l $TARGETLAN_FOR_DETOKENIZER > /dev/null 2>&1 ; then 
-  echo "Defaulting to 'en' as the targetlang for detokenizer."
-  TARGETLAN_FOR_DETOKENIZER=en
-fi
 
 
 # for running this command, qsub is allowed, although we're going to submit jobs ourselves
@@ -163,6 +153,17 @@ function die() { echo "\$@" >&2 ; echo FAILED > \$mydir/eman.status ; exit 1 ; }
 
 export SCRIPTS_ROOTDIR=$SCRIPTS_ROOTDIR
 echo export SCRIPTS_ROOTDIR=$SCRIPTS_ROOTDIR
+export REFAUG=$REFAUG
+
+# clone some important executables
+../../scripts/wiseln $MOSESCMD ./moses || die "Failed to clone moses"
+
+TARGETLAN_FOR_DETOKENIZER=\`echo \$REFAUG | sed 's/^\(..\).*/\1/'\`
+if ! echo "test" | \$SCRIPTS_ROOTDIR/recaser/detokenizer.perl \
+       -u -l \$TARGETLAN_FOR_DETOKENIZER > /dev/null 2>&1 ; then 
+  echo "Defaulting to 'en' as the targetlang for detokenizer."
+  TARGETLAN_FOR_DETOKENIZER=en
+fi
 
 ## Clone the moses.ini and source files
 \$SCRIPTS_ROOTDIR/training/clone_moses_model.pl \\
@@ -173,7 +174,7 @@ echo export SCRIPTS_ROOTDIR=$SCRIPTS_ROOTDIR
 
 cat evaluation.in | ../../scripts/qruncmd -jobs=30 -split-to-size=5000 ./toa.job || die "Failed to filter and translate"
 
-ls alignment0* | sort -n | xargs cat | sed 's/ $//' | gzip -c > alignment.gz
+ls alignment0* | sort -n | xargs cat | sed 's/ $//' | sed -r 's/([0-9]+)-([0-9]+)/\2-\1/g' | gzip -c > alignment.gz
 ls evaluation0*.opt.out.gz | sort -n | xargs zcat | sed 's/ $//' | gzip -c > evaluation.opt.out.gz
 
 mkdir ../augmented_corpora/$TESTCORP-toa
