correcting translate for new moses.ini format

diff --git a/playground/eman.seeds/translate b/playground/eman.seeds/translate
--- a/playground/eman.seeds/translate
+++ b/playground/eman.seeds/translate
@@ -179,10 +179,23 @@ if [ ! -e moses.ini ]; then
     --symlink \\
     $MERTSTEPDIR/moses.ini \\
   || die "Failed to clone the full model"
-  \$SCRIPTS_ROOTDIR/ems/support/reuse-weights.perl \\
-    $MERTSTEPDIR/mert-tuning/"$iterprefix"moses.ini \\
-    < ./moses.ini > moses.mertweights.ini \\
-  || die "Failed to apply weights from mert"
+  
+  if [ -x \$SCRIPTS_ROOTDIR/ems/support/substitute-weights.perl ]; then
+        echo "Detected Moses with substitute-weights - using that"
+
+        \$SCRIPTS_ROOTDIR/ems/support/substitute-weights.perl \\
+        moses.ini \\ 
+        $MERTSTEPDIR/mert-tuning/"$iterprefix"moses.ini \\
+        moses.mertweights.ini \\
+        || die "Failed to apply weights from mert"
+  else
+        echo "Undetected Moses with substitute-weights - using reuse-weights.perl"
+
+        \$SCRIPTS_ROOTDIR/ems/support/reuse-weights.perl \\
+        $MERTSTEPDIR/mert-tuning/"$iterprefix"moses.ini \\
+        < ./moses.ini > moses.mertweights.ini \\
+        || die "Failed to apply weights from mert"
+  fi
   \$SCRIPTS_ROOTDIR/training/absolutize_moses_model.pl \\
     \`pwd\`/moses.mertweights.ini > moses.abs.ini \\
   || die "Failed to absolutize"
