Další podmínka, bez které nefunguje eman continue.

diff --git a/playground/eman.seeds/translate b/playground/eman.seeds/translate
--- a/playground/eman.seeds/translate
+++ b/playground/eman.seeds/translate
@@ -130,17 +130,19 @@ fi
 
 
 function mkcorpus() {
-  $PLAYGROUND/corpman --wait \$1 || die "Failed to prepare \$1"
-  step_file_col=(\$($PLAYGROUND/corpman \$1))
-  if [ "\${step_file_col[2]}" == "-1" ]; then
-    STEPPATH=\$(eman path \${step_file_col[0]})
-    $PLAYGROUND/../scripts/wiseln \$STEPPATH/\${step_file_col[1]} \\
-      corpus.\$2.gz \
-    || die "Failed to clone \$2 corpus \$1"
-  else
-    echo "Selecting the column from \$step_file_col"
-    eval \$($PLAYGROUND/corpman --cmd \$1) \\
-    | gzip -c > corpus.\$2.gz
+  if [ ! -e corpus.\$2.gz ]; then
+    $PLAYGROUND/corpman --wait \$1 || die "Failed to prepare \$1"
+    step_file_col=(\$($PLAYGROUND/corpman \$1))
+    if [ "\${step_file_col[2]}" == "-1" ]; then
+      STEPPATH=\$(eman path \${step_file_col[0]})
+      $PLAYGROUND/../scripts/wiseln \$STEPPATH/\${step_file_col[1]} \\
+        corpus.\$2.gz \
+      || die "Failed to clone \$2 corpus \$1"
+    else
+      echo "Selecting the column from \$step_file_col"
+      eval \$($PLAYGROUND/corpman --cmd \$1) \\
+      | gzip -c > corpus.\$2.gz
+    fi
   fi
 }
 
