adapted for new eman
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@2819 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/difhyp b/playground/difhyp
--- a/playground/difhyp
+++ b/playground/difhyp
@@ -5,30 +5,26 @@ function die() {
   exit 1
 }
 
-a=$1
-b=$2
-
-for prefix in eval mert 2step; do
-  if [ -e exp.$prefix.$a ]; then
-    a=exp.$prefix.$a
-  fi
-  if [ -e exp.$prefix.$b ]; then
-    b=exp.$prefix.$b
-  fi
-done
+a=$(eman path --readonly $1)
+b=$(eman path --readonly $2)
 
 [ -d "$a" ] || die "Missing $a"
 [ -d "$b" ] || die "Missing $b"
+
+a=$(first_existing $a/corpus.translation $a/translated.gz)
+b=$(first_existing $b/corpus.translation $b/translated.gz)
+[ -f "$a" ] || die "Missing $a"
+[ -f "$b" ] || die "Missing $b"
 
 echo Diffing $a and $b
 
 tmp=/tmp/difhyp.$$
 
-echo `cat $a/BLEU.opt` $a > $tmp.a
-echo `cat $b/BLEU.opt` $b > $tmp.b
+#echo `cat $a/BLEU.opt` $a > $tmp.a
+#echo `cat $b/BLEU.opt` $b > $tmp.b
 
-cat $a/evaluation.opt.txt >> $tmp.a
-cat $b/evaluation.opt.txt >> $tmp.b
+autocat $a >> $tmp.a
+autocat $b >> $tmp.b
 
 ziplines --delim $tmp.a $tmp.b | less -S
 
