adapting for eman, untested
git-svn-id: https://svn.ms.mff.cuni.cz/svn/statmt/trunk@1619 85e76b90-d0e1-47da-8fde-e7818187306d

diff --git a/playground/mertcontinue b/playground/mertcontinue
--- a/playground/mertcontinue
+++ b/playground/mertcontinue
@@ -1,5 +1,5 @@
 #!/bin/bash
-# simple script to restart a mert experiment that failed
+# simple script to continue a mert experiment that failed
 
 function die() {
   echo "$@" >&2
@@ -9,17 +9,16 @@ set -o pipefail
 
 [ ! -z "$1" ] || die "usage: $0 exp-identifier"
 
-e=`./manager.pl --guess $1`
+e=`eman guess $1`
 
 [ -d $e ] || die "Not an experiment: $e";
 
-perl -i~ -pe 's/^(.*(clone_moses|absolutize_moses))/# $1/; s/(mert-moses.pl)/$1 --continue/;' $e/command \
-|| die "Failed to modify command"
+perl -i~ -pe 's/^(.*(clone_moses|absolutize_moses))/# $1/; s/(mert-moses.pl)/$1 --continue/;' $e/eman.command \
+|| die "Failed to modify eman.command"
 
-rm -rf $e/FAILED $e/mert-tuning/filtered
+rm -rf $e/mert-tuning/filtered
 
-echo "Now run:"
-cd $e
-echo "  cd $e; nohup nice bash command >> " log.* "&"
+echo "Now check $e/eman.command and start it over:"
+echo "  eman continue $e"
 
 
